// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1
{

    /// <summary>
    /// Template defines a blueprint for the created Secret resource.
    /// </summary>
    public class ClusterPushSecretSpecPushSecretSpecTemplateArgs : global::Pulumi.ResourceArgs
    {
        [Input("data")]
        private InputMap<string>? _data;
        public InputMap<string> Data
        {
            get => _data ?? (_data = new InputMap<string>());
            set => _data = value;
        }

        /// <summary>
        /// EngineVersion specifies the template engine version
        /// that should be used to compile/execute the
        /// template specified in .data and .templateFrom[].
        /// </summary>
        [Input("engineVersion")]
        public Input<string>? EngineVersion { get; set; }

        [Input("mergePolicy")]
        public Input<string>? MergePolicy { get; set; }

        [Input("metadata")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecTemplateMetadataArgs>? Metadata { get; set; }

        [Input("templateFrom")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecTemplateTemplateFromArgs>? _templateFrom;
        public InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecTemplateTemplateFromArgs> TemplateFrom
        {
            get => _templateFrom ?? (_templateFrom = new InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecTemplateTemplateFromArgs>());
            set => _templateFrom = value;
        }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public ClusterPushSecretSpecPushSecretSpecTemplateArgs()
        {
        }
        public static new ClusterPushSecretSpecPushSecretSpecTemplateArgs Empty => new ClusterPushSecretSpecPushSecretSpecTemplateArgs();
    }
}
