// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1
{

    /// <summary>
    /// Select a Secret to Push.
    /// </summary>
    public class ClusterPushSecretSpecPushSecretSpecSelectorSecretPatchArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the Secret.
        /// The Secret must exist in the same namespace as the PushSecret manifest.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("selector")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecSelectorSecretSelectorPatchArgs>? Selector { get; set; }

        public ClusterPushSecretSpecPushSecretSpecSelectorSecretPatchArgs()
        {
        }
        public static new ClusterPushSecretSpecPushSecretSpecSelectorSecretPatchArgs Empty => new ClusterPushSecretSpecPushSecretSpecSelectorSecretPatchArgs();
    }
}
