// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1
{

    /// <summary>
    /// Point to a generator to create a Secret.
    /// </summary>
    public class ClusterPushSecretSpecPushSecretSpecSelectorGeneratorRefArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specify the apiVersion of the generator resource
        /// </summary>
        [Input("apiVersion")]
        public Input<string>? ApiVersion { get; set; }

        /// <summary>
        /// Specify the Kind of the generator resource
        /// </summary>
        [Input("kind")]
        public Input<string>? Kind { get; set; }

        /// <summary>
        /// Specify the name of the generator resource
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public ClusterPushSecretSpecPushSecretSpecSelectorGeneratorRefArgs()
        {
        }
        public static new ClusterPushSecretSpecPushSecretSpecSelectorGeneratorRefArgs Empty => new ClusterPushSecretSpecPushSecretSpecSelectorGeneratorRefArgs();
    }
}
