// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1
{

    public class ClusterPushSecretStatusArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretStatusConditionsArgs>? _conditions;
        public InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretStatusConditionsArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretStatusConditionsArgs>());
            set => _conditions = value;
        }

        [Input("failedNamespaces")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretStatusFailedNamespacesArgs>? _failedNamespaces;

        /// <summary>
        /// Failed namespaces are the namespaces that failed to apply an PushSecret
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretStatusFailedNamespacesArgs> FailedNamespaces
        {
            get => _failedNamespaces ?? (_failedNamespaces = new InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretStatusFailedNamespacesArgs>());
            set => _failedNamespaces = value;
        }

        [Input("provisionedNamespaces")]
        private InputList<string>? _provisionedNamespaces;

        /// <summary>
        /// ProvisionedNamespaces are the namespaces where the ClusterPushSecret has secrets
        /// </summary>
        public InputList<string> ProvisionedNamespaces
        {
            get => _provisionedNamespaces ?? (_provisionedNamespaces = new InputList<string>());
            set => _provisionedNamespaces = value;
        }

        [Input("pushSecretName")]
        public Input<string>? PushSecretName { get; set; }

        public ClusterPushSecretStatusArgs()
        {
        }
        public static new ClusterPushSecretStatusArgs Empty => new ClusterPushSecretStatusArgs();
    }
}
