// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1
{

    /// <summary>
    /// Remote Refs to push to providers.
    /// </summary>
    public class ClusterPushSecretSpecPushSecretSpecDataMatchRemoteRefArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the property in the resulting secret
        /// </summary>
        [Input("property")]
        public Input<string>? Property { get; set; }

        /// <summary>
        /// Name of the resulting provider secret.
        /// </summary>
        [Input("remoteKey")]
        public Input<string>? RemoteKey { get; set; }

        public ClusterPushSecretSpecPushSecretSpecDataMatchRemoteRefArgs()
        {
        }
        public static new ClusterPushSecretSpecPushSecretSpecDataMatchRemoteRefArgs Empty => new ClusterPushSecretSpecPushSecretSpecDataMatchRemoteRefArgs();
    }
}
