// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1
{

    public class ClusterPushSecretSpecArgs : global::Pulumi.ResourceArgs
    {
        [Input("namespaceSelectors")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecNamespaceSelectorsArgs>? _namespaceSelectors;

        /// <summary>
        /// A list of labels to select by to find the Namespaces to create the ExternalSecrets in. The selectors are ORed.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecNamespaceSelectorsArgs> NamespaceSelectors
        {
            get => _namespaceSelectors ?? (_namespaceSelectors = new InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecNamespaceSelectorsArgs>());
            set => _namespaceSelectors = value;
        }

        [Input("pushSecretMetadata")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretMetadataArgs>? PushSecretMetadata { get; set; }

        /// <summary>
        /// The name of the push secrets to be created.
        /// Defaults to the name of the ClusterPushSecret
        /// </summary>
        [Input("pushSecretName")]
        public Input<string>? PushSecretName { get; set; }

        [Input("pushSecretSpec")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecArgs>? PushSecretSpec { get; set; }

        /// <summary>
        /// The time in which the controller should reconcile its objects and recheck namespaces for labels.
        /// </summary>
        [Input("refreshTime")]
        public Input<string>? RefreshTime { get; set; }

        public ClusterPushSecretSpecArgs()
        {
        }
        public static new ClusterPushSecretSpecArgs Empty => new ClusterPushSecretSpecArgs();
    }
}
