// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1
{

    /// <summary>
    /// The Secret Selector (k8s source) for the Push Secret
    /// </summary>
    public class ClusterPushSecretSpecPushSecretSpecSelectorArgs : global::Pulumi.ResourceArgs
    {
        [Input("generatorRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecSelectorGeneratorRefArgs>? GeneratorRef { get; set; }

        [Input("secret")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecSelectorSecretArgs>? Secret { get; set; }

        public ClusterPushSecretSpecPushSecretSpecSelectorArgs()
        {
        }
        public static new ClusterPushSecretSpecPushSecretSpecSelectorArgs Empty => new ClusterPushSecretSpecPushSecretSpecSelectorArgs();
    }
}
