// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1
{

    /// <summary>
    /// PushSecretSpec defines what to do with the secrets.
    /// </summary>
    public class ClusterPushSecretSpecPushSecretSpecPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("data")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecDataPatchArgs>? _data;

        /// <summary>
        /// Secret Data that should be pushed to providers
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecDataPatchArgs> Data
        {
            get => _data ?? (_data = new InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecDataPatchArgs>());
            set => _data = value;
        }

        /// <summary>
        /// Deletion Policy to handle Secrets in the provider.
        /// </summary>
        [Input("deletionPolicy")]
        public Input<string>? DeletionPolicy { get; set; }

        /// <summary>
        /// The Interval to which External Secrets will try to push a secret definition
        /// </summary>
        [Input("refreshInterval")]
        public Input<string>? RefreshInterval { get; set; }

        [Input("secretStoreRefs")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.SecretStoreRefPatchArgs>? _secretStoreRefs;
        public InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.SecretStoreRefPatchArgs> SecretStoreRefs
        {
            get => _secretStoreRefs ?? (_secretStoreRefs = new InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.SecretStoreRefPatchArgs>());
            set => _secretStoreRefs = value;
        }

        [Input("selector")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecSelectorPatchArgs>? Selector { get; set; }

        [Input("template")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecTemplatePatchArgs>? Template { get; set; }

        /// <summary>
        /// UpdatePolicy to handle Secrets in the provider.
        /// </summary>
        [Input("updatePolicy")]
        public Input<string>? UpdatePolicy { get; set; }

        public ClusterPushSecretSpecPushSecretSpecPatchArgs()
        {
        }
        public static new ClusterPushSecretSpecPushSecretSpecPatchArgs Empty => new ClusterPushSecretSpecPushSecretSpecPatchArgs();
    }
}
