// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1
{

    /// <summary>
    /// PushSecretStatus indicates the history of the status of PushSecret.
    /// </summary>
    public class PushSecretStatusArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.PushSecretStatusConditionsArgs>? _conditions;
        public InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.PushSecretStatusConditionsArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.PushSecretStatusConditionsArgs>());
            set => _conditions = value;
        }

        /// <summary>
        /// refreshTime is the time and date the external secret was fetched and
        /// the target secret updated
        /// </summary>
        [Input("refreshTime")]
        public Input<string>? RefreshTime { get; set; }

        [Input("syncedPushSecrets")]
        private InputMap<ImmutableDictionary<string, ImmutableDictionary<string, string>>>? _syncedPushSecrets;

        /// <summary>
        /// Synced PushSecrets, including secrets that already exist in provider.
        /// Matches secret stores to PushSecretData that was stored to that secret store.
        /// </summary>
        public InputMap<ImmutableDictionary<string, ImmutableDictionary<string, string>>> SyncedPushSecrets
        {
            get => _syncedPushSecrets ?? (_syncedPushSecrets = new InputMap<ImmutableDictionary<string, ImmutableDictionary<string, string>>>());
            set => _syncedPushSecrets = value;
        }

        /// <summary>
        /// SyncedResourceVersion keeps track of the last synced version.
        /// </summary>
        [Input("syncedResourceVersion")]
        public Input<string>? SyncedResourceVersion { get; set; }

        public PushSecretStatusArgs()
        {
        }
        public static new PushSecretStatusArgs Empty => new PushSecretStatusArgs();
    }
}
