// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1
{

    public class PushSecretSpecDataArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Used to define a conversion Strategy for the secret keys
        /// </summary>
        [Input("conversionStrategy")]
        public Input<string>? ConversionStrategy { get; set; }

        [Input("match")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.PushSecretSpecDataMatchArgs>? Match { get; set; }

        [Input("metadata")]
        private InputMap<object>? _metadata;

        /// <summary>
        /// Metadata is metadata attached to the secret.
        /// The structure of metadata is provider specific, please look it up in the provider documentation.
        /// </summary>
        public InputMap<object> Metadata
        {
            get => _metadata ?? (_metadata = new InputMap<object>());
            set => _metadata = value;
        }

        public PushSecretSpecDataArgs()
        {
        }
        public static new PushSecretSpecDataArgs Empty => new PushSecretSpecDataArgs();
    }
}
