// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1
{

    /// <summary>
    /// Match a given Secret Key to be pushed to the provider.
    /// </summary>
    public class PushSecretSpecDataMatchPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("remoteRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.PushSecretSpecDataMatchRemoteRefPatchArgs>? RemoteRef { get; set; }

        /// <summary>
        /// Secret Key to be pushed
        /// </summary>
        [Input("secretKey")]
        public Input<string>? SecretKey { get; set; }

        public PushSecretSpecDataMatchPatchArgs()
        {
        }
        public static new PushSecretSpecDataMatchPatchArgs Empty => new PushSecretSpecDataMatchPatchArgs();
    }
}
