// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1
{

    public class PushSecretSpecTemplateTemplateFromSecretPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("items")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.PushSecretSpecTemplateTemplateFromSecretItemsPatchArgs>? _items;

        /// <summary>
        /// A list of keys in the ConfigMap/Secret to use as templates for Secret data
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.PushSecretSpecTemplateTemplateFromSecretItemsPatchArgs> Items
        {
            get => _items ?? (_items = new InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Alpha1.PushSecretSpecTemplateTemplateFromSecretItemsPatchArgs>());
            set => _items = value;
        }

        /// <summary>
        /// The name of the ConfigMap/Secret resource
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public PushSecretSpecTemplateTemplateFromSecretPatchArgs()
        {
        }
        public static new PushSecretSpecTemplateTemplateFromSecretPatchArgs Empty => new PushSecretSpecTemplateTemplateFromSecretPatchArgs();
    }
}
