// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1
{

    [OutputType]
    public sealed class ClusterPushSecretSpecPushSecretSpecSecretStoreRefsPatch
    {
        /// <summary>
        /// Kind of the SecretStore resource (SecretStore or ClusterSecretStore)
        /// </summary>
        public readonly string Kind;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecSecretStoreRefsLabelSelectorPatch LabelSelector;
        /// <summary>
        /// Optionally, sync to the SecretStore of the given name
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private ClusterPushSecretSpecPushSecretSpecSecretStoreRefsPatch(
            string kind,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecSecretStoreRefsLabelSelectorPatch labelSelector,

            string name)
        {
            Kind = kind;
            LabelSelector = labelSelector;
            Name = name;
        }
    }
}
