// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1
{

    [OutputType]
    public sealed class ClusterPushSecretSpecPatch
    {
        /// <summary>
        /// A list of labels to select by to find the Namespaces to create the ExternalSecrets in. The selectors are ORed.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecNamespaceSelectorsPatch> NamespaceSelectors;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretMetadataPatch PushSecretMetadata;
        /// <summary>
        /// The name of the push secrets to be created.
        /// Defaults to the name of the ClusterPushSecret
        /// </summary>
        public readonly string PushSecretName;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecPatch PushSecretSpec;
        /// <summary>
        /// The time in which the controller should reconcile its objects and recheck namespaces for labels.
        /// </summary>
        public readonly string RefreshTime;

        [OutputConstructor]
        private ClusterPushSecretSpecPatch(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecNamespaceSelectorsPatch> namespaceSelectors,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretMetadataPatch pushSecretMetadata,

            string pushSecretName,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecPatch pushSecretSpec,

            string refreshTime)
        {
            NamespaceSelectors = namespaceSelectors;
            PushSecretMetadata = pushSecretMetadata;
            PushSecretName = pushSecretName;
            PushSecretSpec = pushSecretSpec;
            RefreshTime = refreshTime;
        }
    }
}
