// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1
{

    [OutputType]
    public sealed class ClusterPushSecretSpecPushSecretSpecDataPatch
    {
        /// <summary>
        /// Used to define a conversion Strategy for the secret keys
        /// </summary>
        public readonly string ConversionStrategy;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecDataMatchPatch Match;
        /// <summary>
        /// Metadata is metadata attached to the secret.
        /// The structure of metadata is provider specific, please look it up in the provider documentation.
        /// </summary>
        public readonly ImmutableDictionary<string, object> Metadata;

        [OutputConstructor]
        private ClusterPushSecretSpecPushSecretSpecDataPatch(
            string conversionStrategy,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecDataMatchPatch match,

            ImmutableDictionary<string, object> metadata)
        {
            ConversionStrategy = conversionStrategy;
            Match = match;
            Metadata = metadata;
        }
    }
}
