// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1
{

    /// <summary>
    /// PushSecretSpec defines what to do with the secrets.
    /// </summary>
    [OutputType]
    public sealed class ClusterPushSecretSpecPushSecretSpec
    {
        /// <summary>
        /// Secret Data that should be pushed to providers
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecData> Data;
        /// <summary>
        /// Deletion Policy to handle Secrets in the provider.
        /// </summary>
        public readonly string DeletionPolicy;
        /// <summary>
        /// The Interval to which External Secrets will try to push a secret definition
        /// </summary>
        public readonly string RefreshInterval;
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecSecretStoreRefs> SecretStoreRefs;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecSelector Selector;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecTemplate Template;
        /// <summary>
        /// UpdatePolicy to handle Secrets in the provider.
        /// </summary>
        public readonly string UpdatePolicy;

        [OutputConstructor]
        private ClusterPushSecretSpecPushSecretSpec(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecData> data,

            string deletionPolicy,

            string refreshInterval,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecSecretStoreRefs> secretStoreRefs,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecSelector selector,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.ClusterPushSecretSpecPushSecretSpecTemplate template,

            string updatePolicy)
        {
            Data = data;
            DeletionPolicy = deletionPolicy;
            RefreshInterval = refreshInterval;
            SecretStoreRefs = secretStoreRefs;
            Selector = selector;
            Template = template;
            UpdatePolicy = updatePolicy;
        }
    }
}
