// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1
{

    /// <summary>
    /// The Secret Selector (k8s source) for the Push Secret
    /// </summary>
    [OutputType]
    public sealed class PushSecretSpecSelector
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.PushSecretSpecSelectorGeneratorRef GeneratorRef;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.PushSecretSpecSelectorSecret Secret;

        [OutputConstructor]
        private PushSecretSpecSelector(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.PushSecretSpecSelectorGeneratorRef generatorRef,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.PushSecretSpecSelectorSecret secret)
        {
            GeneratorRef = generatorRef;
            Secret = secret;
        }
    }
}
