// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1
{

    /// <summary>
    /// PushSecretStatus indicates the history of the status of PushSecret.
    /// </summary>
    [OutputType]
    public sealed class PushSecretStatus
    {
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.PushSecretStatusConditions> Conditions;
        /// <summary>
        /// refreshTime is the time and date the external secret was fetched and
        /// the target secret updated
        /// </summary>
        public readonly string RefreshTime;
        /// <summary>
        /// Synced PushSecrets, including secrets that already exist in provider.
        /// Matches secret stores to PushSecretData that was stored to that secret store.
        /// </summary>
        public readonly ImmutableDictionary<string, ImmutableDictionary<string, Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.PushSecretStatusSyncedPushSecrets>> SyncedPushSecrets;
        /// <summary>
        /// SyncedResourceVersion keeps track of the last synced version.
        /// </summary>
        public readonly string SyncedResourceVersion;

        [OutputConstructor]
        private PushSecretStatus(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.PushSecretStatusConditions> conditions,

            string refreshTime,

            ImmutableDictionary<string, ImmutableDictionary<string, Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.PushSecretStatusSyncedPushSecrets>> syncedPushSecrets,

            string syncedResourceVersion)
        {
            Conditions = conditions;
            RefreshTime = refreshTime;
            SyncedPushSecrets = syncedPushSecrets;
            SyncedResourceVersion = syncedResourceVersion;
        }
    }
}
