// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1
{

    /// <summary>
    /// PushSecretData defines data to be pushed to the provider and associated metadata.
    /// </summary>
    [OutputType]
    public sealed class PushSecretStatusSyncedPushSecrets
    {   
        /// <summary>
        /// Used to define a conversion Strategy for the secret keys
        /// </summary>
        public readonly string ConversionStrategy;
        
        /// <summary>
        /// Match a given Secret Key to be pushed to the provider.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.PushSecretStatusSyncedPushSecretsMatch Match;

        [OutputConstructor]
        private PushSecretStatusSyncedPushSecrets(
            string conversionStrategy,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.PushSecretStatusSyncedPushSecretsMatch match
        )
        {
            ConversionStrategy = conversionStrategy;
            Match = match;
        }
    }
}
