// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1
{

    /// <summary>
    /// Select a Secret to Push.
    /// </summary>
    [OutputType]
    public sealed class PushSecretSpecSelectorSecretPatch
    {
        /// <summary>
        /// Name of the Secret.
        /// The Secret must exist in the same namespace as the PushSecret manifest.
        /// </summary>
        public readonly string Name;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.PushSecretSpecSelectorSecretSelectorPatch Selector;

        [OutputConstructor]
        private PushSecretSpecSelectorSecretPatch(
            string name,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.PushSecretSpecSelectorSecretSelectorPatch selector)
        {
            Name = name;
            Selector = selector;
        }
    }
}
