// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1
{

    /// <summary>
    /// PushSecretData defines data to be pushed to the provider and associated metadata.
    /// </summary>
    [OutputType]
    public sealed class PushSecretStatusSyncedPushSecretsMatch
    {   
        /// <summary>
        /// Remote Refs to push to providers.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.PushSecretStatusSyncedPushSecretsMatchRemoteRef RemoteRef;
        
        public readonly string? SecretKey;

        [OutputConstructor]
        private PushSecretStatusSyncedPushSecretsMatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Alpha1.PushSecretStatusSyncedPushSecretsMatchRemoteRef remoteRef,

            string secretKey
        )
        {
            RemoteRef = remoteRef;
            SecretKey = secretKey;
        }
    }
}
