// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth configures how the operator authenticates with Akeyless.
    /// </summary>
    [OutputType]
    public sealed class AkeylessProviderAuthSecretRefPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AkeylessProviderAuthSecretRefKubernetesAuthPatch KubernetesAuth;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AkeylessProviderAuthSecretRefSecretRefPatch SecretRef;

        [OutputConstructor]
        private AkeylessProviderAuthSecretRefPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AkeylessProviderAuthSecretRefKubernetesAuthPatch kubernetesAuth,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AkeylessProviderAuthSecretRefSecretRefPatch secretRef)
        {
            KubernetesAuth = kubernetesAuth;
            SecretRef = secretRef;
        }
    }
}
