// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Akeyless configures this store to sync secrets using Akeyless Vault provider
    /// </summary>
    [OutputType]
    public sealed class AkeylessProviderPatch
    {
        /// <summary>
        /// Akeyless GW API Url from which the secrets to be fetched from.
        /// </summary>
        public readonly string AkeylessGWApiURL;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AkeylessProviderAuthSecretRefPatch AuthSecretRef;
        /// <summary>
        /// PEM/base64 encoded CA bundle used to validate Akeyless Gateway certificate. Only used
        /// if the AkeylessGWApiURL URL is using HTTPS protocol. If not set the system root certificates
        /// are used to validate the TLS connection.
        /// </summary>
        public readonly string CaBundle;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AkeylessProviderCaProviderPatch CaProvider;

        [OutputConstructor]
        private AkeylessProviderPatch(
            string akeylessGWApiURL,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AkeylessProviderAuthSecretRefPatch authSecretRef,

            string caBundle,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AkeylessProviderCaProviderPatch caProvider)
        {
            AkeylessGWApiURL = akeylessGWApiURL;
            AuthSecretRef = authSecretRef;
            CaBundle = caBundle;
            CaProvider = caProvider;
        }
    }
}
