// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Kubernetes authenticates with Akeyless by passing the ServiceAccount
    /// token stored in the named Secret resource.
    /// </summary>
    [OutputType]
    public sealed class AkeylessProviderAuthSecretRefKubernetesAuth
    {
        /// <summary>
        /// the Akeyless Kubernetes auth-method access-id
        /// </summary>
        public readonly string AccessID;
        /// <summary>
        /// Kubernetes-auth configuration name in Akeyless-Gateway
        /// </summary>
        public readonly string K8sConfName;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AkeylessProviderAuthSecretRefKubernetesAuthSecretRef SecretRef;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AkeylessProviderAuthSecretRefKubernetesAuthServiceAccountRef ServiceAccountRef;

        [OutputConstructor]
        private AkeylessProviderAuthSecretRefKubernetesAuth(
            string accessID,

            string k8sConfName,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AkeylessProviderAuthSecretRefKubernetesAuthSecretRef secretRef,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AkeylessProviderAuthSecretRefKubernetesAuthServiceAccountRef serviceAccountRef)
        {
            AccessID = accessID;
            K8sConfName = k8sConfName;
            SecretRef = secretRef;
            ServiceAccountRef = serviceAccountRef;
        }
    }
}
