// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Alibaba configures this store to sync secrets using Alibaba Cloud provider
    /// </summary>
    [OutputType]
    public sealed class AlibabaProvider
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AlibabaProviderAuth Auth;
        /// <summary>
        /// Alibaba Region to be used for the provider
        /// </summary>
        public readonly string RegionID;

        [OutputConstructor]
        private AlibabaProvider(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AlibabaProviderAuth auth,

            string regionID)
        {
            Auth = auth;
            RegionID = regionID;
        }
    }
}
