// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Authenticate against AWS using service account tokens.
    /// </summary>
    [OutputType]
    public sealed class AwsProviderAuthJwtPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AwsProviderAuthJwtServiceAccountRefPatch ServiceAccountRef;

        [OutputConstructor]
        private AwsProviderAuthJwtPatch(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AwsProviderAuthJwtServiceAccountRefPatch serviceAccountRef)
        {
            ServiceAccountRef = serviceAccountRef;
        }
    }
}
