// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// AWS configures this store to sync secrets using AWS Secret Manager provider
    /// </summary>
    [OutputType]
    public sealed class AwsProvider
    {
        /// <summary>
        /// AdditionalRoles is a chained list of Role ARNs which the provider will sequentially assume before assuming the Role
        /// </summary>
        public readonly ImmutableArray<string> AdditionalRoles;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AwsProviderAuth Auth;
        /// <summary>
        /// AWS External ID set on assumed IAM roles
        /// </summary>
        public readonly string ExternalID;
        /// <summary>
        /// Prefix adds a prefix to all retrieved values.
        /// </summary>
        public readonly string Prefix;
        /// <summary>
        /// AWS Region to be used for the provider
        /// </summary>
        public readonly string Region;
        /// <summary>
        /// Role is a Role ARN which the provider will assume
        /// </summary>
        public readonly string Role;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AwsProviderSecretsManager SecretsManager;
        /// <summary>
        /// Service defines which service should be used to fetch the secrets
        /// </summary>
        public readonly string Service;
        /// <summary>
        /// AWS STS assume role session tags
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AwsProviderSessionTags> SessionTags;
        /// <summary>
        /// AWS STS assume role transitive session tags. Required when multiple rules are used with the provider
        /// </summary>
        public readonly ImmutableArray<string> TransitiveTagKeys;

        [OutputConstructor]
        private AwsProvider(
            ImmutableArray<string> additionalRoles,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AwsProviderAuth auth,

            string externalID,

            string prefix,

            string region,

            string role,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AwsProviderSecretsManager secretsManager,

            string service,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AwsProviderSessionTags> sessionTags,

            ImmutableArray<string> transitiveTagKeys)
        {
            AdditionalRoles = additionalRoles;
            Auth = auth;
            ExternalID = externalID;
            Prefix = prefix;
            Region = region;
            Role = role;
            SecretsManager = secretsManager;
            Service = service;
            SessionTags = sessionTags;
            TransitiveTagKeys = transitiveTagKeys;
        }
    }
}
