// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// APIKey If not provided then ClientID/ClientSecret become required.
    /// </summary>
    [OutputType]
    public sealed class BeyondtrustProviderAuthApiKeyPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.BeyondtrustProviderAuthApiKeySecretRefPatch SecretRef;
        /// <summary>
        /// Value can be specified directly to set a value without using a secret.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private BeyondtrustProviderAuthApiKeyPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.BeyondtrustProviderAuthApiKeySecretRefPatch secretRef,

            string value)
        {
            SecretRef = secretRef;
            Value = value;
        }
    }
}
