// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// BitwardenSecretsManagerSecretRef contains the credential ref to the bitwarden instance.
    /// </summary>
    [OutputType]
    public sealed class BitwardensecretsmanagerProviderAuthSecretRef
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.BitwardensecretsmanagerProviderAuthSecretRefCredentials Credentials;

        [OutputConstructor]
        private BitwardensecretsmanagerProviderAuthSecretRef(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.BitwardensecretsmanagerProviderAuthSecretRefCredentials credentials)
        {
            Credentials = credentials;
        }
    }
}
