// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// ChefAuthSecretRef holds secret references for chef server login credentials.
    /// </summary>
    [OutputType]
    public sealed class ChefProviderAuthSecretRefPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ChefProviderAuthSecretRefPrivateKeySecretRefPatch PrivateKeySecretRef;

        [OutputConstructor]
        private ChefProviderAuthSecretRefPatch(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ChefProviderAuthSecretRefPrivateKeySecretRefPatch privateKeySecretRef)
        {
            PrivateKeySecretRef = privateKeySecretRef;
        }
    }
}
