// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    [OutputType]
    public sealed class ClusterExternalSecretSpecExternalSecretSpecDataFromRewritePatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ClusterExternalSecretSpecExternalSecretSpecDataFromRewriteMergePatch Merge;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ClusterExternalSecretSpecExternalSecretSpecDataFromRewriteRegexpPatch Regexp;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ClusterExternalSecretSpecExternalSecretSpecDataFromRewriteTransformPatch Transform;

        [OutputConstructor]
        private ClusterExternalSecretSpecExternalSecretSpecDataFromRewritePatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ClusterExternalSecretSpecExternalSecretSpecDataFromRewriteMergePatch merge,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ClusterExternalSecretSpecExternalSecretSpecDataFromRewriteRegexpPatch regexp,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ClusterExternalSecretSpecExternalSecretSpecDataFromRewriteTransformPatch transform)
        {
            Merge = merge;
            Regexp = regexp;
            Transform = transform;
        }
    }
}
