// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Used to configure the provider. Only one provider may be set
    /// </summary>
    [OutputType]
    public sealed class ClusterSecretStoreSpecProvider
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AkeylessProvider Akeyless;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AlibabaProvider Alibaba;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AwsProvider Aws;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AzurekvProvider Azurekv;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.BeyondtrustProvider Beyondtrust;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.BitwardensecretsmanagerProvider Bitwardensecretsmanager;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ChefProvider Chef;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.CloudrusmProvider Cloudrusm;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ConjurProvider Conjur;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.DelineaProvider Delinea;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.DeviceProvider42 Device42;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.DopplerProvider Doppler;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.FakeProvider Fake;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.FortanixProvider Fortanix;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.GcpsmProvider Gcpsm;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.GithubProvider Github;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.GitlabProvider Gitlab;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.IbmProvider Ibm;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProvider Infisical;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KeepersecurityProvider Keepersecurity;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProvider Kubernetes;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OnboardbaseProvider Onboardbase;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OnepasswordProvider Onepassword;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OnepasswordProviderSDK OnepasswordSDK;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OracleProvider Oracle;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.PassboltProvider Passbolt;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.PassworddepotProvider Passworddepot;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.PreviderProvider Previder;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.PulumiProvider Pulumi;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ScalewayProvider Scaleway;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.SecretserverProvider Secretserver;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.SenhaseguraProvider Senhasegura;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProvider Vault;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.WebhookProvider Webhook;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.YandexcertificatemanagerProvider Yandexcertificatemanager;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.YandexlockboxProvider Yandexlockbox;

        [OutputConstructor]
        private ClusterSecretStoreSpecProvider(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AkeylessProvider akeyless,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AlibabaProvider alibaba,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AwsProvider aws,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.AzurekvProvider azurekv,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.BeyondtrustProvider beyondtrust,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.BitwardensecretsmanagerProvider bitwardensecretsmanager,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ChefProvider chef,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.CloudrusmProvider cloudrusm,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ConjurProvider conjur,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.DelineaProvider delinea,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.DeviceProvider42 device42,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.DopplerProvider doppler,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.FakeProvider fake,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.FortanixProvider fortanix,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.GcpsmProvider gcpsm,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.GithubProvider github,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.GitlabProvider gitlab,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.IbmProvider ibm,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProvider infisical,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KeepersecurityProvider keepersecurity,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProvider kubernetes,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OnboardbaseProvider onboardbase,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OnepasswordProvider onepassword,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OnepasswordProviderSDK onepasswordSDK,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OracleProvider oracle,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.PassboltProvider passbolt,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.PassworddepotProvider passworddepot,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.PreviderProvider previder,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.PulumiProvider pulumi,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ScalewayProvider scaleway,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.SecretserverProvider secretserver,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.SenhaseguraProvider senhasegura,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProvider vault,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.WebhookProvider webhook,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.YandexcertificatemanagerProvider yandexcertificatemanager,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.YandexlockboxProvider yandexlockbox)
        {
            Akeyless = akeyless;
            Alibaba = alibaba;
            Aws = aws;
            Azurekv = azurekv;
            Beyondtrust = beyondtrust;
            Bitwardensecretsmanager = bitwardensecretsmanager;
            Chef = chef;
            Cloudrusm = cloudrusm;
            Conjur = conjur;
            Delinea = delinea;
            Device42 = device42;
            Doppler = doppler;
            Fake = fake;
            Fortanix = fortanix;
            Gcpsm = gcpsm;
            Github = github;
            Gitlab = gitlab;
            Ibm = ibm;
            Infisical = infisical;
            Keepersecurity = keepersecurity;
            Kubernetes = kubernetes;
            Onboardbase = onboardbase;
            Onepassword = onepassword;
            OnepasswordSDK = onepasswordSDK;
            Oracle = oracle;
            Passbolt = passbolt;
            Passworddepot = passworddepot;
            Previder = previder;
            Pulumi = pulumi;
            Scaleway = scaleway;
            Secretserver = secretserver;
            Senhasegura = senhasegura;
            Vault = vault;
            Webhook = webhook;
            Yandexcertificatemanager = yandexcertificatemanager;
            Yandexlockbox = yandexlockbox;
        }
    }
}
