// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    [OutputType]
    public sealed class ClusterExternalSecretSpecExternalSecretSpecTargetTemplateTemplateFromSecretItems
    {
        /// <summary>
        /// A key in the ConfigMap/Secret
        /// </summary>
        public readonly string Key;
        public readonly string TemplateAs;

        [OutputConstructor]
        private ClusterExternalSecretSpecExternalSecretSpecTargetTemplateTemplateFromSecretItems(
            string key,

            string templateAs)
        {
            Key = key;
            TemplateAs = templateAs;
        }
    }
}
