// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// GeneratorRef points to a generator custom resource.
    /// </summary>
    [OutputType]
    public sealed class ClusterExternalSecretSpecExternalSecretSpecDataFromSourceRefGeneratorRef
    {
        /// <summary>
        /// Specify the apiVersion of the generator resource
        /// </summary>
        public readonly string ApiVersion;
        /// <summary>
        /// Specify the Kind of the generator resource
        /// </summary>
        public readonly string Kind;
        /// <summary>
        /// Specify the name of the generator resource
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private ClusterExternalSecretSpecExternalSecretSpecDataFromSourceRefGeneratorRef(
            string apiVersion,

            string kind,

            string name)
        {
            ApiVersion = apiVersion;
            Kind = kind;
            Name = name;
        }
    }
}
