// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// ClusterSecretStoreCondition describes a condition by which to choose namespaces to process ExternalSecrets in
    /// for a ClusterSecretStore instance.
    /// </summary>
    [OutputType]
    public sealed class ClusterSecretStoreSpecConditionsPatch
    {
        /// <summary>
        /// Choose namespaces by using regex matching
        /// </summary>
        public readonly ImmutableArray<string> NamespaceRegexes;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ClusterSecretStoreSpecConditionsNamespaceSelectorPatch NamespaceSelector;
        /// <summary>
        /// Choose namespaces by name
        /// </summary>
        public readonly ImmutableArray<string> Namespaces;

        [OutputConstructor]
        private ClusterSecretStoreSpecConditionsPatch(
            ImmutableArray<string> namespaceRegexes,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ClusterSecretStoreSpecConditionsNamespaceSelectorPatch namespaceSelector,

            ImmutableArray<string> namespaces)
        {
            NamespaceRegexes = namespaceRegexes;
            NamespaceSelector = namespaceSelector;
            Namespaces = namespaces;
        }
    }
}
