// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Used to configure http retries if failed
    /// </summary>
    [OutputType]
    public sealed class ClusterSecretStoreSpecRetrySettingsPatch
    {
        public readonly int MaxRetries;
        public readonly string RetryInterval;

        [OutputConstructor]
        private ClusterSecretStoreSpecRetrySettingsPatch(
            int maxRetries,

            string retryInterval)
        {
            MaxRetries = maxRetries;
            RetryInterval = retryInterval;
        }
    }
}
