// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Delinea DevOps Secrets Vault
    /// https://docs.delinea.com/online-help/products/devops-secrets-vault/current
    /// </summary>
    [OutputType]
    public sealed class DelineaProvider
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.DelineaProviderClientId ClientId;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.DelineaProviderClientSecret ClientSecret;
        /// <summary>
        /// Tenant is the chosen hostname / site name.
        /// </summary>
        public readonly string Tenant;
        /// <summary>
        /// TLD is based on the server location that was chosen during provisioning.
        /// If unset, defaults to "com".
        /// </summary>
        public readonly string Tld;
        /// <summary>
        /// URLTemplate
        /// If unset, defaults to "https://%s.secretsvaultcloud.%s/v1/%s%s".
        /// </summary>
        public readonly string UrlTemplate;

        [OutputConstructor]
        private DelineaProvider(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.DelineaProviderClientId clientId,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.DelineaProviderClientSecret clientSecret,

            string tenant,

            string tld,

            string urlTemplate)
        {
            ClientId = clientId;
            ClientSecret = clientSecret;
            Tenant = tenant;
            Tld = tld;
            UrlTemplate = urlTemplate;
        }
    }
}
