// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth configures how the Operator authenticates with the Doppler API
    /// </summary>
    [OutputType]
    public sealed class DopplerProviderAuth
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.DopplerProviderAuthSecretRef SecretRef;

        [OutputConstructor]
        private DopplerProviderAuth(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.DopplerProviderAuthSecretRef secretRef)
        {
            SecretRef = secretRef;
        }
    }
}
