// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Doppler configures this store to sync secrets using the Doppler provider
    /// </summary>
    [OutputType]
    public sealed class DopplerProvider
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.DopplerProviderAuth Auth;
        /// <summary>
        /// Doppler config (required if not using a Service Token)
        /// </summary>
        public readonly string Config;
        /// <summary>
        /// Format enables the downloading of secrets as a file (string)
        /// </summary>
        public readonly string Format;
        /// <summary>
        /// Environment variable compatible name transforms that change secret names to a different format
        /// </summary>
        public readonly string NameTransformer;
        /// <summary>
        /// Doppler project (required if not using a Service Token)
        /// </summary>
        public readonly string Project;

        [OutputConstructor]
        private DopplerProvider(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.DopplerProviderAuth auth,

            string config,

            string format,

            string nameTransformer,

            string project)
        {
            Auth = auth;
            Config = config;
            Format = format;
            NameTransformer = nameTransformer;
            Project = project;
        }
    }
}
