// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    [OutputType]
    public sealed class ExternalSecretSpecDataFromRewrite
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretSpecDataFromRewriteMerge Merge;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretSpecDataFromRewriteRegexp Regexp;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretSpecDataFromRewriteTransform Transform;

        [OutputConstructor]
        private ExternalSecretSpecDataFromRewrite(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretSpecDataFromRewriteMerge merge,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretSpecDataFromRewriteRegexp regexp,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretSpecDataFromRewriteTransform transform)
        {
            Merge = merge;
            Regexp = regexp;
            Transform = transform;
        }
    }
}
