// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Finds secrets based on the name.
    /// </summary>
    [OutputType]
    public sealed class ExternalSecretSpecDataFromFindName
    {
        /// <summary>
        /// Finds secrets base
        /// </summary>
        public readonly string Regexp;

        [OutputConstructor]
        private ExternalSecretSpecDataFromFindName(string regexp)
        {
            Regexp = regexp;
        }
    }
}
