// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// SourceRef allows you to override the source
    /// from which the value will be pulled.
    /// </summary>
    [OutputType]
    public sealed class ExternalSecretSpecDataSourceRef
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretSpecDataSourceRefGeneratorRef GeneratorRef;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretSpecDataSourceRefStoreRef StoreRef;

        [OutputConstructor]
        private ExternalSecretSpecDataSourceRef(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretSpecDataSourceRefGeneratorRef generatorRef,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretSpecDataSourceRefStoreRef storeRef)
        {
            GeneratorRef = generatorRef;
            StoreRef = storeRef;
        }
    }
}
