// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    [OutputType]
    public sealed class ExternalSecretSpecDataFromRewritePatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretSpecDataFromRewriteMergePatch Merge;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretSpecDataFromRewriteRegexpPatch Regexp;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretSpecDataFromRewriteTransformPatch Transform;

        [OutputConstructor]
        private ExternalSecretSpecDataFromRewritePatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretSpecDataFromRewriteMergePatch merge,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretSpecDataFromRewriteRegexpPatch regexp,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretSpecDataFromRewriteTransformPatch transform)
        {
            Merge = merge;
            Regexp = regexp;
            Transform = transform;
        }
    }
}
