// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    [OutputType]
    public sealed class ExternalSecretStatus
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretStatusBinding Binding;
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretStatusConditions> Conditions;
        /// <summary>
        /// refreshTime is the time and date the external secret was fetched and
        /// the target secret updated
        /// </summary>
        public readonly string RefreshTime;
        /// <summary>
        /// SyncedResourceVersion keeps track of the last synced version
        /// </summary>
        public readonly string SyncedResourceVersion;

        [OutputConstructor]
        private ExternalSecretStatus(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretStatusBinding binding,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.ExternalSecretStatusConditions> conditions,

            string refreshTime,

            string syncedResourceVersion)
        {
            Binding = binding;
            Conditions = conditions;
            RefreshTime = refreshTime;
            SyncedResourceVersion = syncedResourceVersion;
        }
    }
}
