// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Fake configures a store with static key/value pairs
    /// </summary>
    [OutputType]
    public sealed class FakeProviderPatch
    {
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.FakeProviderDataPatch> Data;

        [OutputConstructor]
        private FakeProviderPatch(ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.FakeProviderDataPatch> data)
        {
            Data = data;
        }
    }
}
