// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// APIKey is the API token to access SDKMS Applications.
    /// </summary>
    [OutputType]
    public sealed class FortanixProviderApiKeyPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.FortanixProviderApiKeySecretRefPatch SecretRef;

        [OutputConstructor]
        private FortanixProviderApiKeyPatch(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.FortanixProviderApiKeySecretRefPatch secretRef)
        {
            SecretRef = secretRef;
        }
    }
}
