// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Github configures this store to push Github Action secrets using Github API provider
    /// </summary>
    [OutputType]
    public sealed class GithubProviderPatch
    {
        /// <summary>
        /// appID specifies the Github APP that will be used to authenticate the client
        /// </summary>
        public readonly int AppID;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.GithubProviderAuthPatch Auth;
        /// <summary>
        /// environment will be used to fetch secrets from a particular environment within a github repository
        /// </summary>
        public readonly string Environment;
        /// <summary>
        /// installationID specifies the Github APP installation that will be used to authenticate the client
        /// </summary>
        public readonly int InstallationID;
        /// <summary>
        /// organization will be used to fetch secrets from the Github organization
        /// </summary>
        public readonly string Organization;
        /// <summary>
        /// repository will be used to fetch secrets from the Github repository within an organization
        /// </summary>
        public readonly string Repository;
        /// <summary>
        /// Upload URL for enterprise instances. Default to URL.
        /// </summary>
        public readonly string UploadURL;
        /// <summary>
        /// URL configures the Github instance URL. Defaults to https://github.com/.
        /// </summary>
        public readonly string Url;

        [OutputConstructor]
        private GithubProviderPatch(
            int appID,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.GithubProviderAuthPatch auth,

            string environment,

            int installationID,

            string organization,

            string repository,

            string uploadURL,

            string url)
        {
            AppID = appID;
            Auth = auth;
            Environment = environment;
            InstallationID = installationID;
            Organization = organization;
            Repository = repository;
            UploadURL = uploadURL;
            Url = url;
        }
    }
}
