// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// auth configures how secret-manager authenticates with a Github instance.
    /// </summary>
    [OutputType]
    public sealed class GithubProviderAuth
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.GithubProviderAuthPrivateKey PrivateKey;

        [OutputConstructor]
        private GithubProviderAuth(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.GithubProviderAuthPrivateKey privateKey)
        {
            PrivateKey = privateKey;
        }
    }
}
