// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth configures how secret-manager authenticates with a GitLab instance.
    /// </summary>
    [OutputType]
    public sealed class GitlabProviderAuthPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.GitlabProviderAuthSecretRefPatch SecretRef;

        [OutputConstructor]
        private GitlabProviderAuthPatch(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.GitlabProviderAuthSecretRefPatch SecretRef)
        {
            this.SecretRef = SecretRef;
        }
    }
}
