// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// see: https://external-secrets.io/latest/spec/#external-secrets.io/v1alpha1.CAProvider
    /// </summary>
    [OutputType]
    public sealed class GitlabProviderCaProvider
    {
        /// <summary>
        /// The key where the CA certificate can be found in the Secret or ConfigMap.
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// The name of the object located at the provider type.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The namespace the Provider type is in.
        /// Can only be defined when used in a ClusterSecretStore.
        /// </summary>
        public readonly string Namespace;
        /// <summary>
        /// The type of provider to use such as "Secret", or "ConfigMap".
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private GitlabProviderCaProvider(
            string key,

            string name,

            string @namespace,

            string type)
        {
            Key = key;
            Name = name;
            Namespace = @namespace;
            Type = type;
        }
    }
}
