// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// GitLab configures this store to sync secrets using GitLab Variables provider
    /// </summary>
    [OutputType]
    public sealed class GitlabProvider
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.GitlabProviderAuth Auth;
        /// <summary>
        /// Base64 encoded certificate for the GitLab server sdk. The sdk MUST run with HTTPS to make sure no MITM attack
        /// can be performed.
        /// </summary>
        public readonly string CaBundle;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.GitlabProviderCaProvider CaProvider;
        /// <summary>
        /// Environment environment_scope of gitlab CI/CD variables (Please see https://docs.gitlab.com/ee/ci/environments/#create-a-static-environment on how to create environments)
        /// </summary>
        public readonly string Environment;
        /// <summary>
        /// GroupIDs specify, which gitlab groups to pull secrets from. Group secrets are read from left to right followed by the project variables.
        /// </summary>
        public readonly ImmutableArray<string> GroupIDs;
        /// <summary>
        /// InheritFromGroups specifies whether parent groups should be discovered and checked for secrets.
        /// </summary>
        public readonly bool InheritFromGroups;
        /// <summary>
        /// ProjectID specifies a project where secrets are located.
        /// </summary>
        public readonly string ProjectID;
        /// <summary>
        /// URL configures the GitLab instance URL. Defaults to https://gitlab.com/.
        /// </summary>
        public readonly string Url;

        [OutputConstructor]
        private GitlabProvider(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.GitlabProviderAuth auth,

            string caBundle,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.GitlabProviderCaProvider caProvider,

            string environment,

            ImmutableArray<string> groupIDs,

            bool inheritFromGroups,

            string projectID,

            string url)
        {
            Auth = auth;
            CaBundle = caBundle;
            CaProvider = caProvider;
            Environment = environment;
            GroupIDs = groupIDs;
            InheritFromGroups = inheritFromGroups;
            ProjectID = projectID;
            Url = url;
        }
    }
}
