// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    [OutputType]
    public sealed class IbmProviderAuthSecretRefPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.IbmProviderAuthSecretRefSecretApiKeySecretRefPatch SecretApiKeySecretRef;

        [OutputConstructor]
        private IbmProviderAuthSecretRefPatch(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.IbmProviderAuthSecretRefSecretApiKeySecretRefPatch secretApiKeySecretRef)
        {
            SecretApiKeySecretRef = secretApiKeySecretRef;
        }
    }
}
