// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth configures how secret-manager authenticates with the IBM secrets manager.
    /// </summary>
    [OutputType]
    public sealed class IbmProviderAuthPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.IbmProviderAuthContainerAuthPatch ContainerAuth;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.IbmProviderAuthSecretRefPatch SecretRef;

        [OutputConstructor]
        private IbmProviderAuthPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.IbmProviderAuthContainerAuthPatch containerAuth,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.IbmProviderAuthSecretRefPatch secretRef)
        {
            ContainerAuth = containerAuth;
            SecretRef = secretRef;
        }
    }
}
