// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    [OutputType]
    public sealed class InfisicalProviderAuthGcpIamAuthCredentialsPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthGcpIamAuthCredentialsIdentityIdPatch IdentityId;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthGcpIamAuthCredentialsServiceAccountKeyFilePathPatch ServiceAccountKeyFilePath;

        [OutputConstructor]
        private InfisicalProviderAuthGcpIamAuthCredentialsPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthGcpIamAuthCredentialsIdentityIdPatch identityId,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthGcpIamAuthCredentialsServiceAccountKeyFilePathPatch serviceAccountKeyFilePath)
        {
            IdentityId = identityId;
            ServiceAccountKeyFilePath = serviceAccountKeyFilePath;
        }
    }
}
