// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// SecretsScope defines the scope of the secrets within the workspace
    /// </summary>
    [OutputType]
    public sealed class InfisicalProviderSecretsScope
    {
        /// <summary>
        /// EnvironmentSlug is the required slug identifier for the environment.
        /// </summary>
        public readonly string EnvironmentSlug;
        /// <summary>
        /// ExpandSecretReferences indicates whether secret references should be expanded. Defaults to true if not provided.
        /// </summary>
        public readonly bool ExpandSecretReferences;
        /// <summary>
        /// ProjectSlug is the required slug identifier for the project.
        /// </summary>
        public readonly string ProjectSlug;
        /// <summary>
        /// Recursive indicates whether the secrets should be fetched recursively. Defaults to false if not provided.
        /// </summary>
        public readonly bool Recursive;
        /// <summary>
        /// SecretsPath specifies the path to the secrets within the workspace. Defaults to "/" if not provided.
        /// </summary>
        public readonly string SecretsPath;

        [OutputConstructor]
        private InfisicalProviderSecretsScope(
            string environmentSlug,

            bool expandSecretReferences,

            string projectSlug,

            bool recursive,

            string secretsPath)
        {
            EnvironmentSlug = environmentSlug;
            ExpandSecretReferences = expandSecretReferences;
            ProjectSlug = projectSlug;
            Recursive = recursive;
            SecretsPath = secretsPath;
        }
    }
}
