// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth configures how the Operator authenticates with the Infisical API
    /// </summary>
    [OutputType]
    public sealed class InfisicalProviderAuthPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthAzureAuthCredentialsPatch AzureAuthCredentials;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthGcpIamAuthCredentialsPatch GcpIamAuthCredentials;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthGcpIdTokenAuthCredentialsPatch GcpIdTokenAuthCredentials;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthJwtAuthCredentialsPatch JwtAuthCredentials;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthLdapAuthCredentialsPatch LdapAuthCredentials;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthOciAuthCredentialsPatch OciAuthCredentials;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthUniversalAuthCredentialsPatch UniversalAuthCredentials;

        [OutputConstructor]
        private InfisicalProviderAuthPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthAzureAuthCredentialsPatch azureAuthCredentials,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthGcpIamAuthCredentialsPatch gcpIamAuthCredentials,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthGcpIdTokenAuthCredentialsPatch gcpIdTokenAuthCredentials,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthJwtAuthCredentialsPatch jwtAuthCredentials,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthLdapAuthCredentialsPatch ldapAuthCredentials,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthOciAuthCredentialsPatch ociAuthCredentials,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthUniversalAuthCredentialsPatch universalAuthCredentials)
        {
            AzureAuthCredentials = azureAuthCredentials;
            GcpIamAuthCredentials = gcpIamAuthCredentials;
            GcpIdTokenAuthCredentials = gcpIdTokenAuthCredentials;
            JwtAuthCredentials = jwtAuthCredentials;
            LdapAuthCredentials = ldapAuthCredentials;
            OciAuthCredentials = ociAuthCredentials;
            UniversalAuthCredentials = universalAuthCredentials;
        }
    }
}
