// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    [OutputType]
    public sealed class InfisicalProviderAuthGcpIdTokenAuthCredentialsPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthGcpIdTokenAuthCredentialsIdentityIdPatch IdentityId;

        [OutputConstructor]
        private InfisicalProviderAuthGcpIdTokenAuthCredentialsPatch(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthGcpIdTokenAuthCredentialsIdentityIdPatch identityId)
        {
            IdentityId = identityId;
        }
    }
}
