// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    [OutputType]
    public sealed class InfisicalProviderAuthJwtAuthCredentialsPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthJwtAuthCredentialsIdentityIdPatch IdentityId;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthJwtAuthCredentialsJwtPatch Jwt;

        [OutputConstructor]
        private InfisicalProviderAuthJwtAuthCredentialsPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthJwtAuthCredentialsIdentityIdPatch identityId,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthJwtAuthCredentialsJwtPatch jwt)
        {
            IdentityId = identityId;
            Jwt = jwt;
        }
    }
}
