// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth configures how the Operator authenticates with the Infisical API
    /// </summary>
    [OutputType]
    public sealed class InfisicalProviderAuth
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthAzureAuthCredentials AzureAuthCredentials;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthGcpIamAuthCredentials GcpIamAuthCredentials;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthGcpIdTokenAuthCredentials GcpIdTokenAuthCredentials;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthJwtAuthCredentials JwtAuthCredentials;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthLdapAuthCredentials LdapAuthCredentials;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthOciAuthCredentials OciAuthCredentials;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthUniversalAuthCredentials UniversalAuthCredentials;

        [OutputConstructor]
        private InfisicalProviderAuth(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthAzureAuthCredentials azureAuthCredentials,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthGcpIamAuthCredentials gcpIamAuthCredentials,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthGcpIdTokenAuthCredentials gcpIdTokenAuthCredentials,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthJwtAuthCredentials jwtAuthCredentials,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthLdapAuthCredentials ldapAuthCredentials,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthOciAuthCredentials ociAuthCredentials,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthUniversalAuthCredentials universalAuthCredentials)
        {
            AzureAuthCredentials = azureAuthCredentials;
            GcpIamAuthCredentials = gcpIamAuthCredentials;
            GcpIdTokenAuthCredentials = gcpIdTokenAuthCredentials;
            JwtAuthCredentials = jwtAuthCredentials;
            LdapAuthCredentials = ldapAuthCredentials;
            OciAuthCredentials = ociAuthCredentials;
            UniversalAuthCredentials = universalAuthCredentials;
        }
    }
}
