// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    [OutputType]
    public sealed class InfisicalProviderAuthUniversalAuthCredentials
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthUniversalAuthCredentialsClientId ClientId;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthUniversalAuthCredentialsClientSecret ClientSecret;

        [OutputConstructor]
        private InfisicalProviderAuthUniversalAuthCredentials(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthUniversalAuthCredentialsClientId clientId,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.InfisicalProviderAuthUniversalAuthCredentialsClientSecret clientSecret)
        {
            ClientId = clientId;
            ClientSecret = clientSecret;
        }
    }
}
