// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth configures how secret-manager authenticates with a Kubernetes instance.
    /// </summary>
    [OutputType]
    public sealed class KubernetesProviderAuth
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProviderAuthCert Cert;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProviderAuthServiceAccount ServiceAccount;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProviderAuthToken Token;

        [OutputConstructor]
        private KubernetesProviderAuth(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProviderAuthCert cert,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProviderAuthServiceAccount serviceAccount,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProviderAuthToken token)
        {
            Cert = cert;
            ServiceAccount = serviceAccount;
            Token = token;
        }
    }
}
