// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth configures how secret-manager authenticates with a Kubernetes instance.
    /// </summary>
    [OutputType]
    public sealed class KubernetesProviderAuthPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProviderAuthCertPatch Cert;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProviderAuthServiceAccountPatch ServiceAccount;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProviderAuthTokenPatch Token;

        [OutputConstructor]
        private KubernetesProviderAuthPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProviderAuthCertPatch cert,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProviderAuthServiceAccountPatch serviceAccount,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProviderAuthTokenPatch token)
        {
            Cert = cert;
            ServiceAccount = serviceAccount;
            Token = token;
        }
    }
}
