// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Kubernetes configures this store to sync secrets using a Kubernetes cluster provider
    /// </summary>
    [OutputType]
    public sealed class KubernetesProviderPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProviderAuthPatch Auth;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProviderAuthRefPatch AuthRef;
        /// <summary>
        /// Remote namespace to fetch the secrets from
        /// </summary>
        public readonly string RemoteNamespace;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProviderServerPatch Server;

        [OutputConstructor]
        private KubernetesProviderPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProviderAuthPatch auth,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProviderAuthRefPatch authRef,

            string remoteNamespace,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.KubernetesProviderServerPatch server)
        {
            Auth = auth;
            AuthRef = authRef;
            RemoteNamespace = remoteNamespace;
            Server = server;
        }
    }
}
