// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// OnePasswordSDK configures this store to use 1Password's new Go SDK to sync secrets.
    /// </summary>
    [OutputType]
    public sealed class OnepasswordProviderSDK
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OnepasswordProviderSDKAuth Auth;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OnepasswordProviderSDKIntegrationInfo IntegrationInfo;
        /// <summary>
        /// Vault defines the vault's name or uuid to access. Do NOT add op:// prefix. This will be done automatically.
        /// </summary>
        public readonly string Vault;

        [OutputConstructor]
        private OnepasswordProviderSDK(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OnepasswordProviderSDKAuth auth,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OnepasswordProviderSDKIntegrationInfo integrationInfo,

            string vault)
        {
            Auth = auth;
            IntegrationInfo = integrationInfo;
            Vault = vault;
        }
    }
}
