// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth defines the information necessary to authenticate against OnePassword API.
    /// </summary>
    [OutputType]
    public sealed class OnepasswordProviderSDKAuth
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OnepasswordProviderSDKAuthServiceAccountSecretRef ServiceAccountSecretRef;

        [OutputConstructor]
        private OnepasswordProviderSDKAuth(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OnepasswordProviderSDKAuthServiceAccountSecretRef serviceAccountSecretRef)
        {
            ServiceAccountSecretRef = serviceAccountSecretRef;
        }
    }
}
