// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// OnePasswordAuthSecretRef holds secret references for 1Password credentials.
    /// </summary>
    [OutputType]
    public sealed class OnepasswordProviderAuthSecretRefPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OnepasswordProviderAuthSecretRefConnectTokenSecretRefPatch ConnectTokenSecretRef;

        [OutputConstructor]
        private OnepasswordProviderAuthSecretRefPatch(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OnepasswordProviderAuthSecretRefConnectTokenSecretRefPatch connectTokenSecretRef)
        {
            ConnectTokenSecretRef = connectTokenSecretRef;
        }
    }
}
