// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// SecretRef to pass through sensitive information.
    /// </summary>
    [OutputType]
    public sealed class OracleProviderAuthSecretRef
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OracleProviderAuthSecretRefFingerprint Fingerprint;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OracleProviderAuthSecretRefPrivatekey Privatekey;

        [OutputConstructor]
        private OracleProviderAuthSecretRef(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OracleProviderAuthSecretRefFingerprint fingerprint,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.OracleProviderAuthSecretRefPrivatekey privatekey)
        {
            Fingerprint = fingerprint;
            Privatekey = privatekey;
        }
    }
}
