// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth configures how secret-manager authenticates with a Password Depot instance.
    /// </summary>
    [OutputType]
    public sealed class PassworddepotProviderAuthPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.PassworddepotProviderAuthSecretRefPatch SecretRef;

        [OutputConstructor]
        private PassworddepotProviderAuthPatch(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.PassworddepotProviderAuthSecretRefPatch secretRef)
        {
            SecretRef = secretRef;
        }
    }
}
