// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth defines the information necessary to authenticate against Passbolt Server
    /// </summary>
    [OutputType]
    public sealed class PassboltProviderAuthPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.PassboltProviderAuthPasswordSecretRefPatch PasswordSecretRef;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.PassboltProviderAuthPrivateKeySecretRefPatch PrivateKeySecretRef;

        [OutputConstructor]
        private PassboltProviderAuthPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.PassboltProviderAuthPasswordSecretRefPatch passwordSecretRef,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.PassboltProviderAuthPrivateKeySecretRefPatch privateKeySecretRef)
        {
            PasswordSecretRef = passwordSecretRef;
            PrivateKeySecretRef = privateKeySecretRef;
        }
    }
}
