// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// SecretStoreStatus defines the observed state of the SecretStore.
    /// </summary>
    [OutputType]
    public sealed class SecretStoreStatusPatch
    {
        /// <summary>
        /// SecretStoreCapabilities defines the possible operations a SecretStore can do.
        /// </summary>
        public readonly string Capabilities;
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.SecretStoreStatusConditionsPatch> Conditions;

        [OutputConstructor]
        private SecretStoreStatusPatch(
            string capabilities,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.SecretStoreStatusConditionsPatch> conditions)
        {
            Capabilities = capabilities;
            Conditions = conditions;
        }
    }
}
