// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth defines parameters to authenticate in senhasegura
    /// </summary>
    [OutputType]
    public sealed class SenhaseguraProviderAuthPatch
    {
        public readonly string ClientId;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.SenhaseguraProviderAuthClientSecretSecretRefPatch ClientSecretSecretRef;

        [OutputConstructor]
        private SenhaseguraProviderAuthPatch(
            string clientId,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.SenhaseguraProviderAuthClientSecretSecretRefPatch clientSecretSecretRef)
        {
            ClientId = clientId;
            ClientSecretSecretRef = clientSecretSecretRef;
        }
    }
}
