// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Vault configures this store to sync secrets using Hashi provider
    /// </summary>
    [OutputType]
    public sealed class VaultProvider
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuth Auth;
        /// <summary>
        /// PEM encoded CA bundle used to validate Vault server certificate. Only used
        /// if the Server URL is using HTTPS protocol. This parameter is ignored for
        /// plain HTTP protocol connection. If not set the system root certificates
        /// are used to validate the TLS connection.
        /// </summary>
        public readonly string CaBundle;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderCaProvider CaProvider;
        /// <summary>
        /// ForwardInconsistent tells Vault to forward read-after-write requests to the Vault
        /// leader instead of simply retrying within a loop. This can increase performance if
        /// the option is enabled serverside.
        /// https://www.vaultproject.io/docs/configuration/replication#allow_forwarding_via_header
        /// </summary>
        public readonly bool ForwardInconsistent;
        /// <summary>
        /// Headers to be added in Vault request
        /// </summary>
        public readonly ImmutableDictionary<string, string> Headers;
        /// <summary>
        /// Name of the vault namespace. Namespaces is a set of features within Vault Enterprise that allows
        /// Vault environments to support Secure Multi-tenancy. e.g: "ns1".
        /// More about namespaces can be found here https://www.vaultproject.io/docs/enterprise/namespaces
        /// </summary>
        public readonly string Namespace;
        /// <summary>
        /// Path is the mount path of the Vault KV backend endpoint, e.g:
        /// "secret". The v2 KV secret engine version specific "/data" path suffix
        /// for fetching secrets from Vault is optional and will be appended
        /// if not present in specified path.
        /// </summary>
        public readonly string Path;
        /// <summary>
        /// ReadYourWrites ensures isolated read-after-write semantics by
        /// providing discovered cluster replication states in each request.
        /// More information about eventual consistency in Vault can be found here
        /// https://www.vaultproject.io/docs/enterprise/consistency
        /// </summary>
        public readonly bool ReadYourWrites;
        /// <summary>
        /// Server is the connection address for the Vault server, e.g: "https://vault.example.com:8200".
        /// </summary>
        public readonly string Server;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderTls Tls;
        /// <summary>
        /// Version is the Vault KV secret engine version. This can be either "v1" or
        /// "v2". Version defaults to "v2".
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private VaultProvider(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuth auth,

            string caBundle,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderCaProvider caProvider,

            bool forwardInconsistent,

            ImmutableDictionary<string, string> headers,

            string @namespace,

            string path,

            bool readYourWrites,

            string server,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderTls tls,

            string version)
        {
            Auth = auth;
            CaBundle = caBundle;
            CaProvider = caProvider;
            ForwardInconsistent = forwardInconsistent;
            Headers = headers;
            Namespace = @namespace;
            Path = path;
            ReadYourWrites = readYourWrites;
            Server = server;
            Tls = tls;
            Version = version;
        }
    }
}
