// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// UserPass authenticates with Vault by passing username/password pair
    /// </summary>
    [OutputType]
    public sealed class VaultProviderAuthUserPass
    {
        /// <summary>
        /// Path where the UserPassword authentication backend is mounted
        /// in Vault, e.g: "userpass"
        /// </summary>
        public readonly string Path;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthUserPassSecretRef SecretRef;
        /// <summary>
        /// Username is a username used to authenticate using the UserPass Vault
        /// authentication method
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private VaultProviderAuthUserPass(
            string path,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthUserPassSecretRef secretRef,

            string username)
        {
            Path = path;
            SecretRef = secretRef;
            Username = username;
        }
    }
}
