// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// AppRole authenticates with Vault using the App Role auth mechanism,
    /// with the role and secret stored in a Kubernetes Secret resource.
    /// </summary>
    [OutputType]
    public sealed class VaultProviderAuthAppRolePatch
    {
        /// <summary>
        /// Path where the App Role authentication backend is mounted
        /// in Vault, e.g: "approle"
        /// </summary>
        public readonly string Path;
        /// <summary>
        /// RoleID configured in the App Role authentication backend when setting
        /// up the authentication backend in Vault.
        /// </summary>
        public readonly string RoleId;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthAppRoleRoleRefPatch RoleRef;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthAppRoleSecretRefPatch SecretRef;

        [OutputConstructor]
        private VaultProviderAuthAppRolePatch(
            string path,

            string roleId,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthAppRoleRoleRefPatch roleRef,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthAppRoleSecretRefPatch secretRef)
        {
            Path = path;
            RoleId = roleId;
            RoleRef = roleRef;
            SecretRef = secretRef;
        }
    }
}
