// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth configures how secret-manager authenticates with the Vault server.
    /// </summary>
    [OutputType]
    public sealed class VaultProviderAuthPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthAppRolePatch AppRole;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthCertPatch Cert;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthIamPatch Iam;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthJwtPatch Jwt;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthKubernetesPatch Kubernetes;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthLdapPatch Ldap;
        /// <summary>
        /// Name of the vault namespace to authenticate to. This can be different than the namespace your secret is in.
        /// Namespaces is a set of features within Vault Enterprise that allows
        /// Vault environments to support Secure Multi-tenancy. e.g: "ns1".
        /// More about namespaces can be found here https://www.vaultproject.io/docs/enterprise/namespaces
        /// This will default to Vault.Namespace field if set, or empty otherwise
        /// </summary>
        public readonly string Namespace;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthTokenSecretRefPatch TokenSecretRef;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthUserPassPatch UserPass;

        [OutputConstructor]
        private VaultProviderAuthPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthAppRolePatch appRole,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthCertPatch cert,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthIamPatch iam,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthJwtPatch jwt,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthKubernetesPatch kubernetes,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthLdapPatch ldap,

            string @namespace,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthTokenSecretRefPatch tokenSecretRef,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthUserPassPatch userPass)
        {
            AppRole = appRole;
            Cert = cert;
            Iam = iam;
            Jwt = jwt;
            Kubernetes = kubernetes;
            Ldap = ldap;
            Namespace = @namespace;
            TokenSecretRef = tokenSecretRef;
            UserPass = userPass;
        }
    }
}
