// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Cert authenticates with TLS Certificates by passing client certificate, private key and ca certificate
    /// Cert authentication method
    /// </summary>
    [OutputType]
    public sealed class VaultProviderAuthCertPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthCertClientCertPatch ClientCert;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthCertSecretRefPatch SecretRef;

        [OutputConstructor]
        private VaultProviderAuthCertPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthCertClientCertPatch clientCert,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.VaultProviderAuthCertSecretRefPatch secretRef)
        {
            ClientCert = clientCert;
            SecretRef = secretRef;
        }
    }
}
