// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth specifies a authorization protocol. Only one protocol may be set.
    /// </summary>
    [OutputType]
    public sealed class WebhookProviderAuth
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.WebhookProviderAuthNtlm Ntlm;

        [OutputConstructor]
        private WebhookProviderAuth(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.WebhookProviderAuthNtlm ntlm)
        {
            Ntlm = ntlm;
        }
    }
}
