// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1
{

    /// <summary>
    /// The provider for the CA bundle to use to validate Yandex.Cloud server certificate.
    /// </summary>
    [OutputType]
    public sealed class YandexlockboxProviderCaProviderPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.YandexlockboxProviderCaProviderCertSecretRefPatch CertSecretRef;

        [OutputConstructor]
        private YandexlockboxProviderCaProviderPatch(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1.YandexlockboxProviderCaProviderCertSecretRefPatch certSecretRef)
        {
            CertSecretRef = certSecretRef;
        }
    }
}
