// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Crds.ExternalSecrets.V1Beta1
{
    /// <summary>
    /// ClusterSecretStore represents a secure external location for storing secrets, which can be referenced as part of `storeRef` fields.
    /// </summary>
    [CrdsResourceType("kubernetes:external-secrets.io/v1beta1:ClusterSecretStore")]
    public partial class ClusterSecretStore : CustomResource
    {
        /// <summary>
        /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        /// </summary>
        [Output("apiVersion")]
        public Output<string> ApiVersion { get; private set; } = null!;

        /// <summary>
        /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        /// </summary>
        [Output("kind")]
        public Output<string> Kind { get; private set; } = null!;

        /// <summary>
        /// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        /// </summary>
        [Output("metadata")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Meta.V1.ObjectMeta> Metadata { get; private set; } = null!;

        [Output("spec")]
        public Output<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterSecretStoreSpec> Spec { get; private set; } = null!;

        [Output("status")]
        public Output<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterSecretStoreStatus> Status { get; private set; } = null!;


        /// <summary>
        /// Create a ClusterSecretStore resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ClusterSecretStore(string name, Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ClusterSecretStoreArgs? args = null, CustomResourceOptions? options = null)
            : base("kubernetes:external-secrets.io/v1beta1:ClusterSecretStore", name, MakeArgs(args), MakeResourceOptions(options, ""))
        {
        }
        internal ClusterSecretStore(string name, ImmutableDictionary<string, object?> dictionary, CustomResourceOptions? options = null)
            : base("kubernetes:external-secrets.io/v1beta1:ClusterSecretStore", name, new DictionaryResourceArgs(dictionary), MakeResourceOptions(options, ""))
        {
        }

        private ClusterSecretStore(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("kubernetes:external-secrets.io/v1beta1:ClusterSecretStore", name, null, MakeResourceOptions(options, id))
        {
        }

        private static Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ClusterSecretStoreArgs? MakeArgs(Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ClusterSecretStoreArgs? args)
        {
            args ??= new Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ClusterSecretStoreArgs();
            args.ApiVersion = "external-secrets.io/v1beta1";
            args.Kind = "ClusterSecretStore";
            return args;
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                Aliases =
                {
                    new global::Pulumi.Alias { Type = "kubernetes:external-secrets.io/v1:ClusterSecretStore" },
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ClusterSecretStore resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ClusterSecretStore Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ClusterSecretStore(name, id, options);
        }
    }
}
namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    public class ClusterSecretStoreArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        /// </summary>
        [Input("apiVersion")]
        public Input<string>? ApiVersion { get; set; }

        /// <summary>
        /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        /// </summary>
        [Input("kind")]
        public Input<string>? Kind { get; set; }

        /// <summary>
        /// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        /// </summary>
        [Input("metadata")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Meta.V1.ObjectMetaArgs>? Metadata { get; set; }

        [Input("spec")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ClusterSecretStoreSpecArgs>? Spec { get; set; }

        public ClusterSecretStoreArgs()
        {
        }
        public static new ClusterSecretStoreArgs Empty => new ClusterSecretStoreArgs();
    }
}
