// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Reference to a Secret that contains the details
    /// to authenticate with Akeyless.
    /// </summary>
    [OutputType]
    public sealed class AkeylessProviderAuthSecretRefSecretRef
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AkeylessProviderAuthSecretRefSecretRefAccessID AccessID;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AkeylessProviderAuthSecretRefSecretRefAccessType AccessType;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AkeylessProviderAuthSecretRefSecretRefAccessTypeParam AccessTypeParam;

        [OutputConstructor]
        private AkeylessProviderAuthSecretRefSecretRef(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AkeylessProviderAuthSecretRefSecretRefAccessID accessID,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AkeylessProviderAuthSecretRefSecretRefAccessType accessType,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AkeylessProviderAuthSecretRefSecretRefAccessTypeParam accessTypeParam)
        {
            AccessID = accessID;
            AccessType = accessType;
            AccessTypeParam = accessTypeParam;
        }
    }
}
