// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// AlibabaAuthSecretRef holds secret references for Alibaba credentials.
    /// </summary>
    [OutputType]
    public sealed class AlibabaProviderAuthSecretRefPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AlibabaProviderAuthSecretRefAccessKeyIDSecretRefPatch AccessKeyIDSecretRef;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AlibabaProviderAuthSecretRefAccessKeySecretSecretRefPatch AccessKeySecretSecretRef;

        [OutputConstructor]
        private AlibabaProviderAuthSecretRefPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AlibabaProviderAuthSecretRefAccessKeyIDSecretRefPatch accessKeyIDSecretRef,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AlibabaProviderAuthSecretRefAccessKeySecretSecretRefPatch accessKeySecretSecretRef)
        {
            AccessKeyIDSecretRef = accessKeyIDSecretRef;
            AccessKeySecretSecretRef = accessKeySecretSecretRef;
        }
    }
}
