// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// AlibabaAuth contains a secretRef for credentials.
    /// </summary>
    [OutputType]
    public sealed class AlibabaProviderAuth
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AlibabaProviderAuthRrsa Rrsa;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AlibabaProviderAuthSecretRef SecretRef;

        [OutputConstructor]
        private AlibabaProviderAuth(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AlibabaProviderAuthRrsa rrsa,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AlibabaProviderAuthSecretRef secretRef)
        {
            Rrsa = rrsa;
            SecretRef = secretRef;
        }
    }
}
