// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Authenticate against Alibaba using RRSA.
    /// </summary>
    [OutputType]
    public sealed class AlibabaProviderAuthRrsaPatch
    {
        public readonly string OidcProviderArn;
        public readonly string OidcTokenFilePath;
        public readonly string RoleArn;
        public readonly string SessionName;

        [OutputConstructor]
        private AlibabaProviderAuthRrsaPatch(
            string oidcProviderArn,

            string oidcTokenFilePath,

            string roleArn,

            string sessionName)
        {
            OidcProviderArn = oidcProviderArn;
            OidcTokenFilePath = oidcTokenFilePath;
            RoleArn = roleArn;
            SessionName = sessionName;
        }
    }
}
