// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Authenticate against AWS using service account tokens.
    /// </summary>
    [OutputType]
    public sealed class AwsProviderAuthJwt
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AwsProviderAuthJwtServiceAccountRef ServiceAccountRef;

        [OutputConstructor]
        private AwsProviderAuthJwt(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AwsProviderAuthJwtServiceAccountRef serviceAccountRef)
        {
            ServiceAccountRef = serviceAccountRef;
        }
    }
}
