// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// AWSAuthSecretRef holds secret references for AWS credentials
    /// both AccessKeyID and SecretAccessKey must be defined in order to properly authenticate.
    /// </summary>
    [OutputType]
    public sealed class AwsProviderAuthSecretRefPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AwsProviderAuthSecretRefAccessKeyIDSecretRefPatch AccessKeyIDSecretRef;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AwsProviderAuthSecretRefSecretAccessKeySecretRefPatch SecretAccessKeySecretRef;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AwsProviderAuthSecretRefSessionTokenSecretRefPatch SessionTokenSecretRef;

        [OutputConstructor]
        private AwsProviderAuthSecretRefPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AwsProviderAuthSecretRefAccessKeyIDSecretRefPatch accessKeyIDSecretRef,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AwsProviderAuthSecretRefSecretAccessKeySecretRefPatch secretAccessKeySecretRef,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AwsProviderAuthSecretRefSessionTokenSecretRefPatch sessionTokenSecretRef)
        {
            AccessKeyIDSecretRef = accessKeyIDSecretRef;
            SecretAccessKeySecretRef = secretAccessKeySecretRef;
            SessionTokenSecretRef = sessionTokenSecretRef;
        }
    }
}
