// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Auth defines the information necessary to authenticate against AWS
    /// if not set aws sdk will infer credentials from your environment
    /// see: https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-credentials
    /// </summary>
    [OutputType]
    public sealed class AwsProviderAuthPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AwsProviderAuthJwtPatch Jwt;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AwsProviderAuthSecretRefPatch SecretRef;

        [OutputConstructor]
        private AwsProviderAuthPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AwsProviderAuthJwtPatch jwt,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AwsProviderAuthSecretRefPatch secretRef)
        {
            Jwt = jwt;
            SecretRef = secretRef;
        }
    }
}
