// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// The Azure ClientCertificate of the service principle used for authentication.
    /// </summary>
    [OutputType]
    public sealed class AzurekvProviderAuthSecretRefClientCertificate
    {
        /// <summary>
        /// A key in the referenced Secret.
        /// Some instances of this field may be defaulted, in others it may be required.
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// The name of the Secret resource being referred to.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The namespace of the Secret resource being referred to.
        /// Ignored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent.
        /// </summary>
        public readonly string Namespace;

        [OutputConstructor]
        private AzurekvProviderAuthSecretRefClientCertificate(
            string key,

            string name,

            string @namespace)
        {
            Key = key;
            Name = name;
            Namespace = @namespace;
        }
    }
}
