// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Auth configures how the operator authenticates with Beyondtrust.
    /// </summary>
    [OutputType]
    public sealed class BeyondtrustProviderAuth
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BeyondtrustProviderAuthApiKey ApiKey;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BeyondtrustProviderAuthCertificate Certificate;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BeyondtrustProviderAuthCertificateKey CertificateKey;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BeyondtrustProviderAuthClientId ClientId;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BeyondtrustProviderAuthClientSecret ClientSecret;

        [OutputConstructor]
        private BeyondtrustProviderAuth(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BeyondtrustProviderAuthApiKey apiKey,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BeyondtrustProviderAuthCertificate certificate,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BeyondtrustProviderAuthCertificateKey certificateKey,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BeyondtrustProviderAuthClientId clientId,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BeyondtrustProviderAuthClientSecret clientSecret)
        {
            ApiKey = apiKey;
            Certificate = certificate;
            CertificateKey = certificateKey;
            ClientId = clientId;
            ClientSecret = clientSecret;
        }
    }
}
