// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Auth configures how API server works.
    /// </summary>
    [OutputType]
    public sealed class BeyondtrustProviderServer
    {
        public readonly string ApiUrl;
        public readonly string ApiVersion;
        /// <summary>
        /// Timeout specifies a time limit for requests made by this Client. The timeout includes connection time, any redirects, and reading the response body. Defaults to 45 seconds.
        /// </summary>
        public readonly int ClientTimeOutSeconds;
        /// <summary>
        /// The secret retrieval type. SECRET = Secrets Safe (credential, text, file). MANAGED_ACCOUNT = Password Safe account associated with a system.
        /// </summary>
        public readonly string RetrievalType;
        /// <summary>
        /// A character that separates the folder names.
        /// </summary>
        public readonly string Separator;
        public readonly bool VerifyCA;

        [OutputConstructor]
        private BeyondtrustProviderServer(
            string apiUrl,

            string apiVersion,

            int clientTimeOutSeconds,

            string retrievalType,

            string separator,

            bool verifyCA)
        {
            ApiUrl = apiUrl;
            ApiVersion = apiVersion;
            ClientTimeOutSeconds = clientTimeOutSeconds;
            RetrievalType = retrievalType;
            Separator = separator;
            VerifyCA = verifyCA;
        }
    }
}
