// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Beyondtrust configures this store to sync secrets using Password Safe provider.
    /// </summary>
    [OutputType]
    public sealed class BeyondtrustProvider
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BeyondtrustProviderAuth Auth;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BeyondtrustProviderServer Server;

        [OutputConstructor]
        private BeyondtrustProvider(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BeyondtrustProviderAuth auth,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BeyondtrustProviderServer server)
        {
            Auth = auth;
            Server = server;
        }
    }
}
