// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// BitwardenSecretsManager configures this store to sync secrets using BitwardenSecretsManager provider
    /// </summary>
    [OutputType]
    public sealed class BitwardensecretsmanagerProvider
    {
        public readonly string ApiURL;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BitwardensecretsmanagerProviderAuth Auth;
        public readonly string BitwardenServerSDKURL;
        /// <summary>
        /// Base64 encoded certificate for the bitwarden server sdk. The sdk MUST run with HTTPS to make sure no MITM attack
        /// can be performed.
        /// </summary>
        public readonly string CaBundle;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BitwardensecretsmanagerProviderCaProvider CaProvider;
        public readonly string IdentityURL;
        /// <summary>
        /// OrganizationID determines which organization this secret store manages.
        /// </summary>
        public readonly string OrganizationID;
        /// <summary>
        /// ProjectID determines which project this secret store manages.
        /// </summary>
        public readonly string ProjectID;

        [OutputConstructor]
        private BitwardensecretsmanagerProvider(
            string apiURL,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BitwardensecretsmanagerProviderAuth auth,

            string bitwardenServerSDKURL,

            string caBundle,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BitwardensecretsmanagerProviderCaProvider caProvider,

            string identityURL,

            string organizationID,

            string projectID)
        {
            ApiURL = apiURL;
            Auth = auth;
            BitwardenServerSDKURL = bitwardenServerSDKURL;
            CaBundle = caBundle;
            CaProvider = caProvider;
            IdentityURL = identityURL;
            OrganizationID = organizationID;
            ProjectID = projectID;
        }
    }
}
