// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Auth defines the information necessary to authenticate against chef Server
    /// </summary>
    [OutputType]
    public sealed class ChefProviderAuth
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ChefProviderAuthSecretRef SecretRef;

        [OutputConstructor]
        private ChefProviderAuth(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ChefProviderAuthSecretRef secretRef)
        {
            SecretRef = secretRef;
        }
    }
}
