// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// CSMAuthSecretRef holds secret references for Cloud.ru credentials.
    /// </summary>
    [OutputType]
    public sealed class CloudrusmProviderAuthSecretRefPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.CloudrusmProviderAuthSecretRefAccessKeyIDSecretRefPatch AccessKeyIDSecretRef;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.CloudrusmProviderAuthSecretRefAccessKeySecretSecretRefPatch AccessKeySecretSecretRef;

        [OutputConstructor]
        private CloudrusmProviderAuthSecretRefPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.CloudrusmProviderAuthSecretRefAccessKeyIDSecretRefPatch accessKeyIDSecretRef,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.CloudrusmProviderAuthSecretRefAccessKeySecretSecretRefPatch accessKeySecretSecretRef)
        {
            AccessKeyIDSecretRef = accessKeyIDSecretRef;
            AccessKeySecretSecretRef = accessKeySecretSecretRef;
        }
    }
}
