// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// CloudruSM configures this store to sync secrets using the Cloud.ru Secret Manager provider
    /// </summary>
    [OutputType]
    public sealed class CloudrusmProviderPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.CloudrusmProviderAuthPatch Auth;
        /// <summary>
        /// ProjectID is the project, which the secrets are stored in.
        /// </summary>
        public readonly string ProjectID;

        [OutputConstructor]
        private CloudrusmProviderPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.CloudrusmProviderAuthPatch auth,

            string projectID)
        {
            Auth = auth;
            ProjectID = projectID;
        }
    }
}
