// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// ClusterExternalSecretSpec defines the desired state of ClusterExternalSecret.
    /// </summary>
    [OutputType]
    public sealed class ClusterExternalSecretSpecPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretMetadataPatch ExternalSecretMetadata;
        /// <summary>
        /// The name of the external secrets to be created.
        /// Defaults to the name of the ClusterExternalSecret
        /// </summary>
        public readonly string ExternalSecretName;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecPatch ExternalSecretSpec;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecNamespaceSelectorPatch NamespaceSelector;
        /// <summary>
        /// A list of labels to select by to find the Namespaces to create the ExternalSecrets in. The selectors are ORed.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecNamespaceSelectorsPatch> NamespaceSelectors;
        /// <summary>
        /// Choose namespaces by name. This field is ORed with anything that NamespaceSelectors ends up choosing.
        /// Deprecated: Use NamespaceSelectors instead.
        /// </summary>
        public readonly ImmutableArray<string> Namespaces;
        /// <summary>
        /// The time in which the controller should reconcile its objects and recheck namespaces for labels.
        /// </summary>
        public readonly string RefreshTime;

        [OutputConstructor]
        private ClusterExternalSecretSpecPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretMetadataPatch externalSecretMetadata,

            string externalSecretName,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecPatch externalSecretSpec,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecNamespaceSelectorPatch namespaceSelector,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecNamespaceSelectorsPatch> namespaceSelectors,

            ImmutableArray<string> namespaces,

            string refreshTime)
        {
            ExternalSecretMetadata = externalSecretMetadata;
            ExternalSecretName = externalSecretName;
            ExternalSecretSpec = externalSecretSpec;
            NamespaceSelector = namespaceSelector;
            NamespaceSelectors = namespaceSelectors;
            Namespaces = namespaces;
            RefreshTime = refreshTime;
        }
    }
}
