// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    [OutputType]
    public sealed class ClusterExternalSecretSpecExternalSecretSpecTargetTemplateTemplateFromConfigMapPatch
    {
        /// <summary>
        /// A list of keys in the ConfigMap/Secret to use as templates for Secret data
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecTargetTemplateTemplateFromConfigMapItemsPatch> Items;
        /// <summary>
        /// The name of the ConfigMap/Secret resource
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private ClusterExternalSecretSpecExternalSecretSpecTargetTemplateTemplateFromConfigMapPatch(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecTargetTemplateTemplateFromConfigMapItemsPatch> items,

            string name)
        {
            Items = items;
            Name = name;
        }
    }
}
