// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    [OutputType]
    public sealed class ClusterExternalSecretSpecExternalSecretSpecDataFromPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecDataFromExtractPatch Extract;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecDataFromFindPatch Find;
        /// <summary>
        /// Used to rewrite secret Keys after getting them from the secret Provider
        /// Multiple Rewrite operations can be provided. They are applied in a layered order (first to last)
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecDataFromRewritePatch> Rewrite;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecDataFromSourceRefPatch SourceRef;

        [OutputConstructor]
        private ClusterExternalSecretSpecExternalSecretSpecDataFromPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecDataFromExtractPatch extract,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecDataFromFindPatch find,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecDataFromRewritePatch> rewrite,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecDataFromSourceRefPatch sourceRef)
        {
            Extract = extract;
            Find = find;
            Rewrite = rewrite;
            SourceRef = sourceRef;
        }
    }
}
