// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// ClusterExternalSecretNamespaceFailure represents a failed namespace deployment and it's reason.
    /// </summary>
    [OutputType]
    public sealed class ClusterExternalSecretStatusFailedNamespacesPatch
    {
        /// <summary>
        /// Namespace is the namespace that failed when trying to apply an ExternalSecret
        /// </summary>
        public readonly string Namespace;
        /// <summary>
        /// Reason is why the ExternalSecret failed to apply to the namespace
        /// </summary>
        public readonly string Reason;

        [OutputConstructor]
        private ClusterExternalSecretStatusFailedNamespacesPatch(
            string @namespace,

            string reason)
        {
            Namespace = @namespace;
            Reason = reason;
        }
    }
}
