// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// RemoteRef points to the remote secret and defines
    /// which secret (version/property/..) to fetch.
    /// </summary>
    [OutputType]
    public sealed class ClusterExternalSecretSpecExternalSecretSpecDataRemoteRef
    {
        /// <summary>
        /// Used to define a conversion Strategy
        /// </summary>
        public readonly string ConversionStrategy;
        /// <summary>
        /// Used to define a decoding Strategy
        /// </summary>
        public readonly string DecodingStrategy;
        /// <summary>
        /// Key is the key used in the Provider, mandatory
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// Policy for fetching tags/labels from provider secrets, possible options are Fetch, None. Defaults to None
        /// </summary>
        public readonly string MetadataPolicy;
        /// <summary>
        /// Used to select a specific property of the Provider value (if a map), if supported
        /// </summary>
        public readonly string Property;
        /// <summary>
        /// Used to select a specific version of the Provider value, if supported
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private ClusterExternalSecretSpecExternalSecretSpecDataRemoteRef(
            string conversionStrategy,

            string decodingStrategy,

            string key,

            string metadataPolicy,

            string property,

            string version)
        {
            ConversionStrategy = conversionStrategy;
            DecodingStrategy = decodingStrategy;
            Key = key;
            MetadataPolicy = metadataPolicy;
            Property = property;
            Version = version;
        }
    }
}
