// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Defines authentication settings for connecting to Conjur.
    /// </summary>
    [OutputType]
    public sealed class ConjurProviderAuth
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ConjurProviderAuthApikey Apikey;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ConjurProviderAuthJwt Jwt;

        [OutputConstructor]
        private ConjurProviderAuth(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ConjurProviderAuthApikey apikey,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ConjurProviderAuthJwt jwt)
        {
            Apikey = apikey;
            Jwt = jwt;
        }
    }
}
