// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Conjur configures this store to sync secrets using conjur provider
    /// </summary>
    [OutputType]
    public sealed class ConjurProvider
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ConjurProviderAuth Auth;
        /// <summary>
        /// CABundle is a PEM encoded CA bundle that will be used to validate the Conjur server certificate.
        /// </summary>
        public readonly string CaBundle;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ConjurProviderCaProvider CaProvider;
        /// <summary>
        /// URL is the endpoint of the Conjur instance.
        /// </summary>
        public readonly string Url;

        [OutputConstructor]
        private ConjurProvider(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ConjurProviderAuth auth,

            string caBundle,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ConjurProviderCaProvider caProvider,

            string url)
        {
            Auth = auth;
            CaBundle = caBundle;
            CaProvider = caProvider;
            Url = url;
        }
    }
}
