// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    [OutputType]
    public sealed class DeviceProvider42AuthSecretRef
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.DeviceProvider42AuthSecretRefCredentials Credentials;

        [OutputConstructor]
        private DeviceProvider42AuthSecretRef(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.DeviceProvider42AuthSecretRefCredentials credentials)
        {
            Credentials = credentials;
        }
    }
}
