// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Device42 configures this store to sync secrets using the Device42 provider
    /// </summary>
    [OutputType]
    public sealed class DeviceProvider42Patch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.DeviceProvider42AuthPatch Auth;
        /// <summary>
        /// URL configures the Device42 instance URL.
        /// </summary>
        public readonly string Host;

        [OutputConstructor]
        private DeviceProvider42Patch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.DeviceProvider42AuthPatch auth,

            string host)
        {
            Auth = auth;
            Host = host;
        }
    }
}
