// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// ExternalSecretData defines the connection between the Kubernetes Secret key (spec.data.&lt;key&gt;) and the Provider data.
    /// </summary>
    [OutputType]
    public sealed class ExternalSecretSpecData
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ExternalSecretSpecDataRemoteRef RemoteRef;
        /// <summary>
        /// The key in the Kubernetes Secret to store the value.
        /// </summary>
        public readonly string SecretKey;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ExternalSecretSpecDataSourceRef SourceRef;

        [OutputConstructor]
        private ExternalSecretSpecData(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ExternalSecretSpecDataRemoteRef remoteRef,

            string secretKey,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ExternalSecretSpecDataSourceRef sourceRef)
        {
            RemoteRef = remoteRef;
            SecretKey = secretKey;
            SourceRef = sourceRef;
        }
    }
}
