// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// ExternalSecretTarget defines the Kubernetes Secret to be created
    /// There can be only one target per ExternalSecret.
    /// </summary>
    [OutputType]
    public sealed class ExternalSecretSpecTarget
    {
        /// <summary>
        /// CreationPolicy defines rules on how to create the resulting Secret.
        /// Defaults to "Owner"
        /// </summary>
        public readonly string CreationPolicy;
        /// <summary>
        /// DeletionPolicy defines rules on how to delete the resulting Secret.
        /// Defaults to "Retain"
        /// </summary>
        public readonly string DeletionPolicy;
        /// <summary>
        /// Immutable defines if the final secret will be immutable
        /// </summary>
        public readonly bool Immutable;
        /// <summary>
        /// The name of the Secret resource to be managed.
        /// Defaults to the .metadata.name of the ExternalSecret resource
        /// </summary>
        public readonly string Name;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ExternalSecretSpecTargetTemplate Template;

        [OutputConstructor]
        private ExternalSecretSpecTarget(
            string creationPolicy,

            string deletionPolicy,

            bool immutable,

            string name,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ExternalSecretSpecTargetTemplate template)
        {
            CreationPolicy = creationPolicy;
            DeletionPolicy = deletionPolicy;
            Immutable = immutable;
            Name = name;
            Template = template;
        }
    }
}
