// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    [OutputType]
    public sealed class ExternalSecretSpecTargetTemplateTemplateFromPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ExternalSecretSpecTargetTemplateTemplateFromConfigMapPatch ConfigMap;
        public readonly string Literal;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ExternalSecretSpecTargetTemplateTemplateFromSecretPatch Secret;
        public readonly string Target;

        [OutputConstructor]
        private ExternalSecretSpecTargetTemplateTemplateFromPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ExternalSecretSpecTargetTemplateTemplateFromConfigMapPatch configMap,

            string literal,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ExternalSecretSpecTargetTemplateTemplateFromSecretPatch secret,

            string target)
        {
            ConfigMap = configMap;
            Literal = literal;
            Secret = secret;
            Target = target;
        }
    }
}
