// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    [OutputType]
    public sealed class FakeProviderDataPatch
    {
        public readonly string Key;
        public readonly string Value;
        public readonly string Version;

        [OutputConstructor]
        private FakeProviderDataPatch(
            string key,

            string value,

            string version)
        {
            Key = key;
            Value = value;
            Version = version;
        }
    }
}
