// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Fortanix configures this store to sync secrets using the Fortanix provider
    /// </summary>
    [OutputType]
    public sealed class FortanixProvider
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.FortanixProviderApiKey ApiKey;
        /// <summary>
        /// APIURL is the URL of SDKMS API. Defaults to `sdkms.fortanix.com`.
        /// </summary>
        public readonly string ApiUrl;

        [OutputConstructor]
        private FortanixProvider(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.FortanixProviderApiKey apiKey,

            string apiUrl)
        {
            ApiKey = apiKey;
            ApiUrl = apiUrl;
        }
    }
}
