// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    [OutputType]
    public sealed class GitlabProviderAuthSecretRefPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.GitlabProviderAuthSecretRefAccessTokenPatch AccessToken;

        [OutputConstructor]
        private GitlabProviderAuthSecretRefPatch(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.GitlabProviderAuthSecretRefAccessTokenPatch accessToken)
        {
            AccessToken = accessToken;
        }
    }
}
