// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Auth configures how the Operator authenticates with the Infisical API
    /// </summary>
    [OutputType]
    public sealed class InfisicalProviderAuth
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.InfisicalProviderAuthUniversalAuthCredentials UniversalAuthCredentials;

        [OutputConstructor]
        private InfisicalProviderAuth(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.InfisicalProviderAuthUniversalAuthCredentials universalAuthCredentials)
        {
            UniversalAuthCredentials = universalAuthCredentials;
        }
    }
}
