// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// OnePassword configures this store to sync secrets using the 1Password Cloud provider
    /// </summary>
    [OutputType]
    public sealed class OnepasswordProvider
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.OnepasswordProviderAuth Auth;
        /// <summary>
        /// ConnectHost defines the OnePassword Connect Server to connect to
        /// </summary>
        public readonly string ConnectHost;
        /// <summary>
        /// Vaults defines which OnePassword vaults to search in which order
        /// </summary>
        public readonly ImmutableDictionary<string, int> Vaults;

        [OutputConstructor]
        private OnepasswordProvider(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.OnepasswordProviderAuth auth,

            string connectHost,

            ImmutableDictionary<string, int> vaults)
        {
            Auth = auth;
            ConnectHost = connectHost;
            Vaults = vaults;
        }
    }
}
