// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Configures a store to sync secrets with a Password Depot instance.
    /// </summary>
    [OutputType]
    public sealed class PassworddepotProviderPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PassworddepotProviderAuthPatch Auth;
        /// <summary>
        /// Database to use as source
        /// </summary>
        public readonly string Database;
        /// <summary>
        /// URL configures the Password Depot instance URL.
        /// </summary>
        public readonly string Host;

        [OutputConstructor]
        private PassworddepotProviderPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PassworddepotProviderAuthPatch auth,

            string database,

            string host)
        {
            Auth = auth;
            Database = database;
            Host = host;
        }
    }
}
