// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Auth defines the information necessary to authenticate against Passbolt Server
    /// </summary>
    [OutputType]
    public sealed class PassboltProviderAuth
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PassboltProviderAuthPasswordSecretRef PasswordSecretRef;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PassboltProviderAuthPrivateKeySecretRef PrivateKeySecretRef;

        [OutputConstructor]
        private PassboltProviderAuth(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PassboltProviderAuthPasswordSecretRef passwordSecretRef,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PassboltProviderAuthPrivateKeySecretRef privateKeySecretRef)
        {
            PasswordSecretRef = passwordSecretRef;
            PrivateKeySecretRef = privateKeySecretRef;
        }
    }
}
