// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Used to configure the provider. Only one provider may be set
    /// </summary>
    [OutputType]
    public sealed class PatchProvider
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AkeylessProviderPatch Akeyless;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AlibabaProviderPatch Alibaba;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AwsProviderPatch Aws;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AzurekvProviderPatch Azurekv;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BeyondtrustProviderPatch Beyondtrust;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BitwardensecretsmanagerProviderPatch Bitwardensecretsmanager;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ChefProviderPatch Chef;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.CloudrusmProviderPatch Cloudrusm;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ConjurProviderPatch Conjur;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.DelineaProviderPatch Delinea;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.DeviceProvider42Patch Device42;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.DopplerProviderPatch Doppler;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.FakeProviderPatch Fake;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.FortanixProviderPatch Fortanix;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.GcpsmProviderPatch Gcpsm;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.GithubProviderPatch Github;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.GitlabProviderPatch Gitlab;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.IbmProviderPatch Ibm;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.InfisicalProviderPatch Infisical;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.KeepersecurityProviderPatch Keepersecurity;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.KubernetesProviderPatch Kubernetes;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.OnboardbaseProviderPatch Onboardbase;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.OnepasswordProviderPatch Onepassword;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.OracleProviderPatch Oracle;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PassboltProviderPatch Passbolt;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PassworddepotProviderPatch Passworddepot;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PreviderProviderPatch Previder;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PulumiProviderPatch Pulumi;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ScalewayProviderPatch Scaleway;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.SecretserverProviderPatch Secretserver;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.SenhaseguraProviderPatch Senhasegura;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.VaultProviderPatch Vault;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.WebhookProviderPatch Webhook;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.YandexcertificatemanagerProviderPatch Yandexcertificatemanager;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.YandexlockboxProviderPatch Yandexlockbox;

        [OutputConstructor]
        private PatchProvider(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AkeylessProviderPatch akeyless,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AlibabaProviderPatch alibaba,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AwsProviderPatch aws,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.AzurekvProviderPatch azurekv,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BeyondtrustProviderPatch beyondtrust,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.BitwardensecretsmanagerProviderPatch bitwardensecretsmanager,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ChefProviderPatch chef,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.CloudrusmProviderPatch cloudrusm,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ConjurProviderPatch conjur,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.DelineaProviderPatch delinea,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.DeviceProvider42Patch device42,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.DopplerProviderPatch doppler,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.FakeProviderPatch fake,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.FortanixProviderPatch fortanix,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.GcpsmProviderPatch gcpsm,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.GithubProviderPatch github,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.GitlabProviderPatch gitlab,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.IbmProviderPatch ibm,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.InfisicalProviderPatch infisical,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.KeepersecurityProviderPatch keepersecurity,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.KubernetesProviderPatch kubernetes,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.OnboardbaseProviderPatch onboardbase,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.OnepasswordProviderPatch onepassword,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.OracleProviderPatch oracle,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PassboltProviderPatch passbolt,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PassworddepotProviderPatch passworddepot,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PreviderProviderPatch previder,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PulumiProviderPatch pulumi,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ScalewayProviderPatch scaleway,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.SecretserverProviderPatch secretserver,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.SenhaseguraProviderPatch senhasegura,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.VaultProviderPatch vault,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.WebhookProviderPatch webhook,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.YandexcertificatemanagerProviderPatch yandexcertificatemanager,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.YandexlockboxProviderPatch yandexlockbox)
        {
            Akeyless = akeyless;
            Alibaba = alibaba;
            Aws = aws;
            Azurekv = azurekv;
            Beyondtrust = beyondtrust;
            Bitwardensecretsmanager = bitwardensecretsmanager;
            Chef = chef;
            Cloudrusm = cloudrusm;
            Conjur = conjur;
            Delinea = delinea;
            Device42 = device42;
            Doppler = doppler;
            Fake = fake;
            Fortanix = fortanix;
            Gcpsm = gcpsm;
            Github = github;
            Gitlab = gitlab;
            Ibm = ibm;
            Infisical = infisical;
            Keepersecurity = keepersecurity;
            Kubernetes = kubernetes;
            Onboardbase = onboardbase;
            Onepassword = onepassword;
            Oracle = oracle;
            Passbolt = passbolt;
            Passworddepot = passworddepot;
            Previder = previder;
            Pulumi = pulumi;
            Scaleway = scaleway;
            Secretserver = secretserver;
            Senhasegura = senhasegura;
            Vault = vault;
            Webhook = webhook;
            Yandexcertificatemanager = yandexcertificatemanager;
            Yandexlockbox = yandexlockbox;
        }
    }
}
