// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Previder configures this store to sync secrets using the Previder provider
    /// </summary>
    [OutputType]
    public sealed class PreviderProvider
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PreviderProviderAuth Auth;
        public readonly string BaseUri;

        [OutputConstructor]
        private PreviderProvider(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PreviderProviderAuth auth,

            string baseUri)
        {
            Auth = auth;
            BaseUri = baseUri;
        }
    }
}
