// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// PreviderAuth contains a secretRef for credentials.
    /// </summary>
    [OutputType]
    public sealed class PreviderProviderAuth
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PreviderProviderAuthSecretRef SecretRef;

        [OutputConstructor]
        private PreviderProviderAuth(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PreviderProviderAuthSecretRef secretRef)
        {
            SecretRef = secretRef;
        }
    }
}
