// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// AccessToken is the access tokens to sign in to the Pulumi Cloud Console.
    /// </summary>
    [OutputType]
    public sealed class PulumiProviderAccessToken
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PulumiProviderAccessTokenSecretRef SecretRef;

        [OutputConstructor]
        private PulumiProviderAccessToken(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.PulumiProviderAccessTokenSecretRef secretRef)
        {
            SecretRef = secretRef;
        }
    }
}
