// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// AccessKey is the non-secret part of the api key.
    /// </summary>
    [OutputType]
    public sealed class ScalewayProviderAccessKeyPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ScalewayProviderAccessKeySecretRefPatch SecretRef;
        /// <summary>
        /// Value can be specified directly to set a value without using a secret.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private ScalewayProviderAccessKeyPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ScalewayProviderAccessKeySecretRefPatch secretRef,

            string value)
        {
            SecretRef = secretRef;
            Value = value;
        }
    }
}
