// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Scaleway
    /// </summary>
    [OutputType]
    public sealed class ScalewayProviderPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ScalewayProviderAccessKeyPatch AccessKey;
        /// <summary>
        /// APIURL is the url of the api to use. Defaults to https://api.scaleway.com
        /// </summary>
        public readonly string ApiUrl;
        /// <summary>
        /// ProjectID is the id of your project, which you can find in the console: https://console.scaleway.com/project/settings
        /// </summary>
        public readonly string ProjectId;
        /// <summary>
        /// Region where your secrets are located: https://developers.scaleway.com/en/quickstart/#region-and-zone
        /// </summary>
        public readonly string Region;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ScalewayProviderSecretKeyPatch SecretKey;

        [OutputConstructor]
        private ScalewayProviderPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ScalewayProviderAccessKeyPatch accessKey,

            string apiUrl,

            string projectId,

            string region,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.ScalewayProviderSecretKeyPatch secretKey)
        {
            AccessKey = accessKey;
            ApiUrl = apiUrl;
            ProjectId = projectId;
            Region = region;
            SecretKey = secretKey;
        }
    }
}
