// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// SecretStoreSpec defines the desired state of SecretStore.
    /// </summary>
    [OutputType]
    public sealed class SecretStoreSpec
    {
        /// <summary>
        /// Used to constraint a ClusterSecretStore to specific namespaces. Relevant only to ClusterSecretStore
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.SecretStoreSpecConditions> Conditions;
        /// <summary>
        /// Used to select the correct ESO controller (think: ingress.ingressClassName)
        /// The ESO controller is instantiated with a specific controller name and filters ES based on this property
        /// </summary>
        public readonly string Controller;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.SecretStoreSpecProvider Provider;
        /// <summary>
        /// Used to configure store refresh interval in seconds. Empty or 0 will default to the controller config.
        /// </summary>
        public readonly int RefreshInterval;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.SecretStoreSpecRetrySettings RetrySettings;

        [OutputConstructor]
        private SecretStoreSpec(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.SecretStoreSpecConditions> conditions,

            string controller,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.SecretStoreSpecProvider provider,

            int refreshInterval,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.SecretStoreSpecRetrySettings retrySettings)
        {
            Conditions = conditions;
            Controller = controller;
            Provider = provider;
            RefreshInterval = refreshInterval;
            RetrySettings = retrySettings;
        }
    }
}
