// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Senhasegura configures this store to sync secrets using senhasegura provider
    /// </summary>
    [OutputType]
    public sealed class SenhaseguraProvider
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.SenhaseguraProviderAuth Auth;
        /// <summary>
        /// IgnoreSslCertificate defines if SSL certificate must be ignored
        /// </summary>
        public readonly bool IgnoreSslCertificate;
        /// <summary>
        /// Module defines which senhasegura module should be used to get secrets
        /// </summary>
        public readonly string Module;
        /// <summary>
        /// URL of senhasegura
        /// </summary>
        public readonly string Url;

        [OutputConstructor]
        private SenhaseguraProvider(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.SenhaseguraProviderAuth auth,

            bool ignoreSslCertificate,

            string module,

            string url)
        {
            Auth = auth;
            IgnoreSslCertificate = ignoreSslCertificate;
            Module = module;
            Url = url;
        }
    }
}
