// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Specify a service account with IRSA enabled
    /// </summary>
    [OutputType]
    public sealed class VaultProviderAuthIamJwtPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.VaultProviderAuthIamJwtServiceAccountRefPatch ServiceAccountRef;

        [OutputConstructor]
        private VaultProviderAuthIamJwtPatch(Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.VaultProviderAuthIamJwtServiceAccountRefPatch serviceAccountRef)
        {
            ServiceAccountRef = serviceAccountRef;
        }
    }
}
