// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Iam authenticates with vault by passing a special AWS request signed with AWS IAM credentials
    /// AWS IAM authentication method
    /// </summary>
    [OutputType]
    public sealed class VaultProviderAuthIam
    {
        /// <summary>
        /// AWS External ID set on assumed IAM roles
        /// </summary>
        public readonly string ExternalID;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.VaultProviderAuthIamJwt Jwt;
        /// <summary>
        /// Path where the AWS auth method is enabled in Vault, e.g: "aws"
        /// </summary>
        public readonly string Path;
        /// <summary>
        /// AWS region
        /// </summary>
        public readonly string Region;
        /// <summary>
        /// This is the AWS role to be assumed before talking to vault
        /// </summary>
        public readonly string Role;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.VaultProviderAuthIamSecretRef SecretRef;
        /// <summary>
        /// X-Vault-AWS-IAM-Server-ID is an additional header used by Vault IAM auth method to mitigate against different types of replay attacks. More details here: https://developer.hashicorp.com/vault/docs/auth/aws
        /// </summary>
        public readonly string VaultAwsIamServerID;
        /// <summary>
        /// Vault Role. In vault, a role describes an identity with a set of permissions, groups, or policies you want to attach a user of the secrets engine
        /// </summary>
        public readonly string VaultRole;

        [OutputConstructor]
        private VaultProviderAuthIam(
            string externalID,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.VaultProviderAuthIamJwt jwt,

            string path,

            string region,

            string role,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.VaultProviderAuthIamSecretRef secretRef,

            string vaultAwsIamServerID,

            string vaultRole)
        {
            ExternalID = externalID;
            Jwt = jwt;
            Path = path;
            Region = region;
            Role = role;
            SecretRef = secretRef;
            VaultAwsIamServerID = vaultAwsIamServerID;
            VaultRole = vaultRole;
        }
    }
}
