// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Jwt authenticates with Vault by passing role and JWT token using the
    /// JWT/OIDC authentication method
    /// </summary>
    [OutputType]
    public sealed class VaultProviderAuthJwtPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.VaultProviderAuthJwtKubernetesServiceAccountTokenPatch KubernetesServiceAccountToken;
        /// <summary>
        /// Path where the JWT authentication backend is mounted
        /// in Vault, e.g: "jwt"
        /// </summary>
        public readonly string Path;
        /// <summary>
        /// Role is a JWT role to authenticate using the JWT/OIDC Vault
        /// authentication method
        /// </summary>
        public readonly string Role;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.VaultProviderAuthJwtSecretRefPatch SecretRef;

        [OutputConstructor]
        private VaultProviderAuthJwtPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.VaultProviderAuthJwtKubernetesServiceAccountTokenPatch kubernetesServiceAccountToken,

            string path,

            string role,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.VaultProviderAuthJwtSecretRefPatch secretRef)
        {
            KubernetesServiceAccountToken = kubernetesServiceAccountToken;
            Path = path;
            Role = role;
            SecretRef = secretRef;
        }
    }
}
