// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// KeySecretRef to a key in a Secret resource containing client private key
    /// added to the transport layer when communicating with the Vault server.
    /// If no key for the Secret is specified, external-secret will default to 'tls.key'.
    /// </summary>
    [OutputType]
    public sealed class VaultProviderTlsKeySecretRef
    {
        /// <summary>
        /// A key in the referenced Secret.
        /// Some instances of this field may be defaulted, in others it may be required.
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// The name of the Secret resource being referred to.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The namespace of the Secret resource being referred to.
        /// Ignored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent.
        /// </summary>
        public readonly string Namespace;

        [OutputConstructor]
        private VaultProviderTlsKeySecretRef(
            string key,

            string name,

            string @namespace)
        {
            Key = key;
            Name = name;
            Namespace = @namespace;
        }
    }
}
