// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    [OutputType]
    public sealed class WebhookProviderSecretsPatch
    {
        /// <summary>
        /// Name of this secret in templates
        /// </summary>
        public readonly string Name;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.WebhookProviderSecretsSecretRefPatch SecretRef;

        [OutputConstructor]
        private WebhookProviderSecretsPatch(
            string name,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.WebhookProviderSecretsSecretRefPatch secretRef)
        {
            Name = name;
            SecretRef = secretRef;
        }
    }
}
