// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// NTLMProtocol configures the store to use NTLM for auth
    /// </summary>
    [OutputType]
    public sealed class WebhookProviderAuthNtlmPatch
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.WebhookProviderAuthNtlmPasswordSecretPatch PasswordSecret;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.WebhookProviderAuthNtlmUsernameSecretPatch UsernameSecret;

        [OutputConstructor]
        private WebhookProviderAuthNtlmPatch(
            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.WebhookProviderAuthNtlmPasswordSecretPatch passwordSecret,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.WebhookProviderAuthNtlmUsernameSecretPatch usernameSecret)
        {
            PasswordSecret = passwordSecret;
            UsernameSecret = usernameSecret;
        }
    }
}
