// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// YandexLockbox configures this store to sync secrets using Yandex Lockbox provider
    /// </summary>
    [OutputType]
    public sealed class YandexlockboxProviderPatch
    {
        /// <summary>
        /// Yandex.Cloud API endpoint (e.g. 'api.cloud.yandex.net:443')
        /// </summary>
        public readonly string ApiEndpoint;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.YandexlockboxProviderAuthPatch Auth;
        public readonly Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.YandexlockboxProviderCaProviderPatch CaProvider;

        [OutputConstructor]
        private YandexlockboxProviderPatch(
            string apiEndpoint,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.YandexlockboxProviderAuthPatch auth,

            Pulumi.Kubernetes.Types.Outputs.ExternalSecrets.V1Beta1.YandexlockboxProviderCaProviderPatch caProvider)
        {
            ApiEndpoint = apiEndpoint;
            Auth = auth;
            CaProvider = caProvider;
        }
    }
}
