// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Kubernetes authenticates with Akeyless by passing the ServiceAccount
    /// token stored in the named Secret resource.
    /// </summary>
    public class AkeylessProviderAuthSecretRefKubernetesAuthPatchArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// the Akeyless Kubernetes auth-method access-id
        /// </summary>
        [Input("accessID")]
        public Input<string>? AccessID { get; set; }

        /// <summary>
        /// Kubernetes-auth configuration name in Akeyless-Gateway
        /// </summary>
        [Input("k8sConfName")]
        public Input<string>? K8sConfName { get; set; }

        [Input("secretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.AkeylessProviderAuthSecretRefKubernetesAuthSecretRefPatchArgs>? SecretRef { get; set; }

        [Input("serviceAccountRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.AkeylessProviderAuthSecretRefKubernetesAuthServiceAccountRefPatchArgs>? ServiceAccountRef { get; set; }

        public AkeylessProviderAuthSecretRefKubernetesAuthPatchArgs()
        {
        }
        public static new AkeylessProviderAuthSecretRefKubernetesAuthPatchArgs Empty => new AkeylessProviderAuthSecretRefKubernetesAuthPatchArgs();
    }
}
