// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// AlibabaAuthSecretRef holds secret references for Alibaba credentials.
    /// </summary>
    public class AlibabaProviderAuthSecretRefArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessKeyIDSecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.AlibabaProviderAuthSecretRefAccessKeyIDSecretRefArgs>? AccessKeyIDSecretRef { get; set; }

        [Input("accessKeySecretSecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.AlibabaProviderAuthSecretRefAccessKeySecretSecretRefArgs>? AccessKeySecretSecretRef { get; set; }

        public AlibabaProviderAuthSecretRefArgs()
        {
        }
        public static new AlibabaProviderAuthSecretRefArgs Empty => new AlibabaProviderAuthSecretRefArgs();
    }
}
