// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Alibaba configures this store to sync secrets using Alibaba Cloud provider
    /// </summary>
    public class AlibabaProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("auth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.AlibabaProviderAuthArgs>? Auth { get; set; }

        /// <summary>
        /// Alibaba Region to be used for the provider
        /// </summary>
        [Input("regionID")]
        public Input<string>? RegionID { get; set; }

        public AlibabaProviderArgs()
        {
        }
        public static new AlibabaProviderArgs Empty => new AlibabaProviderArgs();
    }
}
