// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// SecretsManager defines how the provider behaves when interacting with AWS SecretsManager
    /// </summary>
    public class AwsProviderSecretsManagerArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specifies whether to delete the secret without any recovery window. You
        /// can't use both this parameter and RecoveryWindowInDays in the same call.
        /// If you don't use either, then by default Secrets Manager uses a 30 day
        /// recovery window.
        /// see: https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_DeleteSecret.html#SecretsManager-DeleteSecret-request-ForceDeleteWithoutRecovery
        /// </summary>
        [Input("forceDeleteWithoutRecovery")]
        public Input<bool>? ForceDeleteWithoutRecovery { get; set; }

        /// <summary>
        /// The number of days from 7 to 30 that Secrets Manager waits before
        /// permanently deleting the secret. You can't use both this parameter and
        /// ForceDeleteWithoutRecovery in the same call. If you don't use either,
        /// then by default Secrets Manager uses a 30 day recovery window.
        /// see: https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_DeleteSecret.html#SecretsManager-DeleteSecret-request-RecoveryWindowInDays
        /// </summary>
        [Input("recoveryWindowInDays")]
        public Input<int>? RecoveryWindowInDays { get; set; }

        public AwsProviderSecretsManagerArgs()
        {
        }
        public static new AwsProviderSecretsManagerArgs Empty => new AwsProviderSecretsManagerArgs();
    }
}
