// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth defines the information necessary to authenticate against AWS
    /// if not set aws sdk will infer credentials from your environment
    /// see: https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-credentials
    /// </summary>
    public class AwsProviderAuthPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("jwt")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.AwsProviderAuthJwtPatchArgs>? Jwt { get; set; }

        [Input("secretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.AwsProviderAuthSecretRefPatchArgs>? SecretRef { get; set; }

        public AwsProviderAuthPatchArgs()
        {
        }
        public static new AwsProviderAuthPatchArgs Empty => new AwsProviderAuthPatchArgs();
    }
}
