// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Authenticate against AWS using service account tokens.
    /// </summary>
    public class AwsProviderAuthJwtArgs : global::Pulumi.ResourceArgs
    {
        [Input("serviceAccountRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.AwsProviderAuthJwtServiceAccountRefArgs>? ServiceAccountRef { get; set; }

        public AwsProviderAuthJwtArgs()
        {
        }
        public static new AwsProviderAuthJwtArgs Empty => new AwsProviderAuthJwtArgs();
    }
}
