// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth configures how the operator authenticates with Azure. Required for ServicePrincipal auth type. Optional for WorkloadIdentity.
    /// </summary>
    public class AzurekvProviderAuthSecretRefArgs : global::Pulumi.ResourceArgs
    {
        [Input("clientCertificate")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.AzurekvProviderAuthSecretRefClientCertificateArgs>? ClientCertificate { get; set; }

        [Input("clientId")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.AzurekvProviderAuthSecretRefClientIdArgs>? ClientId { get; set; }

        [Input("clientSecret")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.AzurekvProviderAuthSecretRefClientSecretArgs>? ClientSecret { get; set; }

        [Input("tenantId")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.AzurekvProviderAuthSecretRefTenantIdArgs>? TenantId { get; set; }

        public AzurekvProviderAuthSecretRefArgs()
        {
        }
        public static new AzurekvProviderAuthSecretRefArgs Empty => new AzurekvProviderAuthSecretRefArgs();
    }
}
