// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// APIKey If not provided then ClientID/ClientSecret become required.
    /// </summary>
    public class BeyondtrustProviderAuthApiKeyPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("secretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.BeyondtrustProviderAuthApiKeySecretRefPatchArgs>? SecretRef { get; set; }

        /// <summary>
        /// Value can be specified directly to set a value without using a secret.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public BeyondtrustProviderAuthApiKeyPatchArgs()
        {
        }
        public static new BeyondtrustProviderAuthApiKeyPatchArgs Empty => new BeyondtrustProviderAuthApiKeyPatchArgs();
    }
}
