// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth configures how the operator authenticates with Beyondtrust.
    /// </summary>
    public class BeyondtrustProviderAuthArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiKey")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.BeyondtrustProviderAuthApiKeyArgs>? ApiKey { get; set; }

        [Input("certificate")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.BeyondtrustProviderAuthCertificateArgs>? Certificate { get; set; }

        [Input("certificateKey")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.BeyondtrustProviderAuthCertificateKeyArgs>? CertificateKey { get; set; }

        [Input("clientId")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.BeyondtrustProviderAuthClientIdArgs>? ClientId { get; set; }

        [Input("clientSecret")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.BeyondtrustProviderAuthClientSecretArgs>? ClientSecret { get; set; }

        public BeyondtrustProviderAuthArgs()
        {
        }
        public static new BeyondtrustProviderAuthArgs Empty => new BeyondtrustProviderAuthArgs();
    }
}
