// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Beyondtrust configures this store to sync secrets using Password Safe provider.
    /// </summary>
    public class BeyondtrustProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("auth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.BeyondtrustProviderAuthArgs>? Auth { get; set; }

        [Input("server")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.BeyondtrustProviderServerArgs>? Server { get; set; }

        public BeyondtrustProviderArgs()
        {
        }
        public static new BeyondtrustProviderArgs Empty => new BeyondtrustProviderArgs();
    }
}
