// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth configures how secret-manager authenticates with a bitwarden machine account instance.
    /// Make sure that the token being used has permissions on the given secret.
    /// </summary>
    public class BitwardensecretsmanagerProviderAuthPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("secretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.BitwardensecretsmanagerProviderAuthSecretRefPatchArgs>? SecretRef { get; set; }

        public BitwardensecretsmanagerProviderAuthPatchArgs()
        {
        }
        public static new BitwardensecretsmanagerProviderAuthPatchArgs Empty => new BitwardensecretsmanagerProviderAuthPatchArgs();
    }
}
