// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// ChefAuthSecretRef holds secret references for chef server login credentials.
    /// </summary>
    public class ChefProviderAuthSecretRefPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("privateKeySecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.ChefProviderAuthSecretRefPrivateKeySecretRefPatchArgs>? PrivateKeySecretRef { get; set; }

        public ChefProviderAuthSecretRefPatchArgs()
        {
        }
        public static new ChefProviderAuthSecretRefPatchArgs Empty => new ChefProviderAuthSecretRefPatchArgs();
    }
}
