// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// CSMAuthSecretRef holds secret references for Cloud.ru credentials.
    /// </summary>
    public class CloudrusmProviderAuthSecretRefArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessKeyIDSecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.CloudrusmProviderAuthSecretRefAccessKeyIDSecretRefArgs>? AccessKeyIDSecretRef { get; set; }

        [Input("accessKeySecretSecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.CloudrusmProviderAuthSecretRefAccessKeySecretSecretRefArgs>? AccessKeySecretSecretRef { get; set; }

        public CloudrusmProviderAuthSecretRefArgs()
        {
        }
        public static new CloudrusmProviderAuthSecretRefArgs Empty => new CloudrusmProviderAuthSecretRefArgs();
    }
}
