// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    public class ClusterExternalSecretStatusConditionsArgs : global::Pulumi.ResourceArgs
    {
        [Input("message")]
        public Input<string>? Message { get; set; }

        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public ClusterExternalSecretStatusConditionsArgs()
        {
        }
        public static new ClusterExternalSecretStatusConditionsArgs Empty => new ClusterExternalSecretStatusConditionsArgs();
    }
}
