// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// ClusterExternalSecretStatus defines the observed state of ClusterExternalSecret.
    /// </summary>
    public class ClusterExternalSecretStatusArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.ClusterExternalSecretStatusConditionsArgs>? _conditions;
        public InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.ClusterExternalSecretStatusConditionsArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.ClusterExternalSecretStatusConditionsArgs>());
            set => _conditions = value;
        }

        /// <summary>
        /// ExternalSecretName is the name of the ExternalSecrets created by the ClusterExternalSecret
        /// </summary>
        [Input("externalSecretName")]
        public Input<string>? ExternalSecretName { get; set; }

        [Input("failedNamespaces")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.ClusterExternalSecretStatusFailedNamespacesArgs>? _failedNamespaces;

        /// <summary>
        /// Failed namespaces are the namespaces that failed to apply an ExternalSecret
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.ClusterExternalSecretStatusFailedNamespacesArgs> FailedNamespaces
        {
            get => _failedNamespaces ?? (_failedNamespaces = new InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.ClusterExternalSecretStatusFailedNamespacesArgs>());
            set => _failedNamespaces = value;
        }

        [Input("provisionedNamespaces")]
        private InputList<string>? _provisionedNamespaces;

        /// <summary>
        /// ProvisionedNamespaces are the namespaces where the ClusterExternalSecret has secrets
        /// </summary>
        public InputList<string> ProvisionedNamespaces
        {
            get => _provisionedNamespaces ?? (_provisionedNamespaces = new InputList<string>());
            set => _provisionedNamespaces = value;
        }

        public ClusterExternalSecretStatusArgs()
        {
        }
        public static new ClusterExternalSecretStatusArgs Empty => new ClusterExternalSecretStatusArgs();
    }
}
