// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Device42 configures this store to sync secrets using the Device42 provider
    /// </summary>
    public class DeviceProvider42PatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("auth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.DeviceProvider42AuthPatchArgs>? Auth { get; set; }

        /// <summary>
        /// URL configures the Device42 instance URL.
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        public DeviceProvider42PatchArgs()
        {
        }
        public static new DeviceProvider42PatchArgs Empty => new DeviceProvider42PatchArgs();
    }
}
