// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Used to apply string transformation on the secrets.
    /// The resulting key will be the output of the template applied by the operation.
    /// </summary>
    public class ExternalSecretSpecDataFromRewriteTransformArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Used to define the template to apply on the secret name.
        /// `.value ` will specify the secret name in the template.
        /// </summary>
        [Input("template")]
        public Input<string>? Template { get; set; }

        public ExternalSecretSpecDataFromRewriteTransformArgs()
        {
        }
        public static new ExternalSecretSpecDataFromRewriteTransformArgs Empty => new ExternalSecretSpecDataFromRewriteTransformArgs();
    }
}
