// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    public class ExternalSecretSpecDataFromRewritePatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("merge")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.ExternalSecretSpecDataFromRewriteMergePatchArgs>? Merge { get; set; }

        [Input("regexp")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.ExternalSecretSpecDataFromRewriteRegexpPatchArgs>? Regexp { get; set; }

        [Input("transform")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.ExternalSecretSpecDataFromRewriteTransformPatchArgs>? Transform { get; set; }

        public ExternalSecretSpecDataFromRewritePatchArgs()
        {
        }
        public static new ExternalSecretSpecDataFromRewritePatchArgs Empty => new ExternalSecretSpecDataFromRewritePatchArgs();
    }
}
