// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    public class ExternalSecretSpecTargetTemplateTemplateFromSecretItemsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A key in the ConfigMap/Secret
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        [Input("templateAs")]
        public Input<string>? TemplateAs { get; set; }

        public ExternalSecretSpecTargetTemplateTemplateFromSecretItemsArgs()
        {
        }
        public static new ExternalSecretSpecTargetTemplateTemplateFromSecretItemsArgs Empty => new ExternalSecretSpecTargetTemplateTemplateFromSecretItemsArgs();
    }
}
