// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Fake configures a store with static key/value pairs
    /// </summary>
    public class FakeProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("data")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.FakeProviderDataArgs>? _data;
        public InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.FakeProviderDataArgs> Data
        {
            get => _data ?? (_data = new InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.FakeProviderDataArgs>());
            set => _data = value;
        }

        public FakeProviderArgs()
        {
        }
        public static new FakeProviderArgs Empty => new FakeProviderArgs();
    }
}
