// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    public class GcpsmProviderAuthSecretRefArgs : global::Pulumi.ResourceArgs
    {
        [Input("secretAccessKeySecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.GcpsmProviderAuthSecretRefSecretAccessKeySecretRefArgs>? SecretAccessKeySecretRef { get; set; }

        public GcpsmProviderAuthSecretRefArgs()
        {
        }
        public static new GcpsmProviderAuthSecretRefArgs Empty => new GcpsmProviderAuthSecretRefArgs();
    }
}
