// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    public class GcpsmProviderAuthWorkloadIdentityPatchArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ClusterLocation is the location of the cluster
        /// If not specified, it fetches information from the metadata server
        /// </summary>
        [Input("clusterLocation")]
        public Input<string>? ClusterLocation { get; set; }

        /// <summary>
        /// ClusterName is the name of the cluster
        /// If not specified, it fetches information from the metadata server
        /// </summary>
        [Input("clusterName")]
        public Input<string>? ClusterName { get; set; }

        /// <summary>
        /// ClusterProjectID is the project ID of the cluster
        /// If not specified, it fetches information from the metadata server
        /// </summary>
        [Input("clusterProjectID")]
        public Input<string>? ClusterProjectID { get; set; }

        [Input("serviceAccountRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.GcpsmProviderAuthWorkloadIdentityServiceAccountRefPatchArgs>? ServiceAccountRef { get; set; }

        public GcpsmProviderAuthWorkloadIdentityPatchArgs()
        {
        }
        public static new GcpsmProviderAuthWorkloadIdentityPatchArgs Empty => new GcpsmProviderAuthWorkloadIdentityPatchArgs();
    }
}
