// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth defines the information necessary to authenticate against GCP
    /// </summary>
    public class GcpsmProviderAuthArgs : global::Pulumi.ResourceArgs
    {
        [Input("secretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.GcpsmProviderAuthSecretRefArgs>? SecretRef { get; set; }

        [Input("workloadIdentity")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.GcpsmProviderAuthWorkloadIdentityArgs>? WorkloadIdentity { get; set; }

        public GcpsmProviderAuthArgs()
        {
        }
        public static new GcpsmProviderAuthArgs Empty => new GcpsmProviderAuthArgs();
    }
}
