// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth configures how secret-manager authenticates with a GitLab instance.
    /// </summary>
    public class GitlabProviderAuthArgs : global::Pulumi.ResourceArgs
    {
        [Input("SecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.GitlabProviderAuthSecretRefArgs>? SecretRef { get; set; }

        public GitlabProviderAuthArgs()
        {
        }
        public static new GitlabProviderAuthArgs Empty => new GitlabProviderAuthArgs();
    }
}
