// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    public class InfisicalProviderAuthGcpIdTokenAuthCredentialsArgs : global::Pulumi.ResourceArgs
    {
        [Input("identityId")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderAuthGcpIdTokenAuthCredentialsIdentityIdArgs>? IdentityId { get; set; }

        public InfisicalProviderAuthGcpIdTokenAuthCredentialsArgs()
        {
        }
        public static new InfisicalProviderAuthGcpIdTokenAuthCredentialsArgs Empty => new InfisicalProviderAuthGcpIdTokenAuthCredentialsArgs();
    }
}
