// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    public class InfisicalProviderAuthUniversalAuthCredentialsArgs : global::Pulumi.ResourceArgs
    {
        [Input("clientId")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderAuthUniversalAuthCredentialsClientIdArgs>? ClientId { get; set; }

        [Input("clientSecret")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderAuthUniversalAuthCredentialsClientSecretArgs>? ClientSecret { get; set; }

        public InfisicalProviderAuthUniversalAuthCredentialsArgs()
        {
        }
        public static new InfisicalProviderAuthUniversalAuthCredentialsArgs Empty => new InfisicalProviderAuthUniversalAuthCredentialsArgs();
    }
}
