// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    public class InfisicalProviderAuthAzureAuthCredentialsArgs : global::Pulumi.ResourceArgs
    {
        [Input("identityId")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderAuthAzureAuthCredentialsIdentityIdArgs>? IdentityId { get; set; }

        [Input("resource")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderAuthAzureAuthCredentialsResourceArgs>? Resource { get; set; }

        public InfisicalProviderAuthAzureAuthCredentialsArgs()
        {
        }
        public static new InfisicalProviderAuthAzureAuthCredentialsArgs Empty => new InfisicalProviderAuthAzureAuthCredentialsArgs();
    }
}
