// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    public class InfisicalProviderAuthGcpIamAuthCredentialsPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("identityId")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderAuthGcpIamAuthCredentialsIdentityIdPatchArgs>? IdentityId { get; set; }

        [Input("serviceAccountKeyFilePath")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderAuthGcpIamAuthCredentialsServiceAccountKeyFilePathPatchArgs>? ServiceAccountKeyFilePath { get; set; }

        public InfisicalProviderAuthGcpIamAuthCredentialsPatchArgs()
        {
        }
        public static new InfisicalProviderAuthGcpIamAuthCredentialsPatchArgs Empty => new InfisicalProviderAuthGcpIamAuthCredentialsPatchArgs();
    }
}
