// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    public class InfisicalProviderAuthLdapAuthCredentialsArgs : global::Pulumi.ResourceArgs
    {
        [Input("identityId")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderAuthLdapAuthCredentialsIdentityIdArgs>? IdentityId { get; set; }

        [Input("ldapPassword")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderAuthLdapAuthCredentialsLdapPasswordArgs>? LdapPassword { get; set; }

        [Input("ldapUsername")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderAuthLdapAuthCredentialsLdapUsernameArgs>? LdapUsername { get; set; }

        public InfisicalProviderAuthLdapAuthCredentialsArgs()
        {
        }
        public static new InfisicalProviderAuthLdapAuthCredentialsArgs Empty => new InfisicalProviderAuthLdapAuthCredentialsArgs();
    }
}
