// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    public class InfisicalProviderAuthOciAuthCredentialsPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("fingerprint")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderAuthOciAuthCredentialsFingerprintPatchArgs>? Fingerprint { get; set; }

        [Input("identityId")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderAuthOciAuthCredentialsIdentityIdPatchArgs>? IdentityId { get; set; }

        [Input("privateKey")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderAuthOciAuthCredentialsPrivateKeyPatchArgs>? PrivateKey { get; set; }

        [Input("privateKeyPassphrase")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderAuthOciAuthCredentialsPrivateKeyPassphrasePatchArgs>? PrivateKeyPassphrase { get; set; }

        [Input("region")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderAuthOciAuthCredentialsRegionPatchArgs>? Region { get; set; }

        [Input("tenancyId")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderAuthOciAuthCredentialsTenancyIdPatchArgs>? TenancyId { get; set; }

        [Input("userId")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderAuthOciAuthCredentialsUserIdPatchArgs>? UserId { get; set; }

        public InfisicalProviderAuthOciAuthCredentialsPatchArgs()
        {
        }
        public static new InfisicalProviderAuthOciAuthCredentialsPatchArgs Empty => new InfisicalProviderAuthOciAuthCredentialsPatchArgs();
    }
}
