// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Infisical configures this store to sync secrets using the Infisical provider
    /// </summary>
    public class InfisicalProviderPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("auth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderAuthPatchArgs>? Auth { get; set; }

        /// <summary>
        /// HostAPI specifies the base URL of the Infisical API. If not provided, it defaults to "https://app.infisical.com/api".
        /// </summary>
        [Input("hostAPI")]
        public Input<string>? HostAPI { get; set; }

        [Input("secretsScope")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderSecretsScopePatchArgs>? SecretsScope { get; set; }

        public InfisicalProviderPatchArgs()
        {
        }
        public static new InfisicalProviderPatchArgs Empty => new InfisicalProviderPatchArgs();
    }
}
