// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// configures the Kubernetes server Address.
    /// </summary>
    public class KubernetesProviderServerPatchArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// CABundle is a base64-encoded CA certificate
        /// </summary>
        [Input("caBundle")]
        public Input<string>? CaBundle { get; set; }

        [Input("caProvider")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.KubernetesProviderServerCaProviderPatchArgs>? CaProvider { get; set; }

        /// <summary>
        /// configures the Kubernetes server Address.
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public KubernetesProviderServerPatchArgs()
        {
        }
        public static new KubernetesProviderServerPatchArgs Empty => new KubernetesProviderServerPatchArgs();
    }
}
