// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// see: https://external-secrets.io/v0.4.1/spec/#external-secrets.io/v1alpha1.CAProvider
    /// </summary>
    public class KubernetesProviderServerCaProviderPatchArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The key where the CA certificate can be found in the Secret or ConfigMap.
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// The name of the object located at the provider type.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The namespace the Provider type is in.
        /// Can only be defined when used in a ClusterSecretStore.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        /// <summary>
        /// The type of provider to use such as "Secret", or "ConfigMap".
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public KubernetesProviderServerCaProviderPatchArgs()
        {
        }
        public static new KubernetesProviderServerCaProviderPatchArgs Empty => new KubernetesProviderServerCaProviderPatchArgs();
    }
}
