// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth configures how the Operator authenticates with the Onboardbase API
    /// </summary>
    public class OnboardbaseProviderAuthPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiKeyRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.OnboardbaseProviderAuthApiKeyRefPatchArgs>? ApiKeyRef { get; set; }

        [Input("passcodeRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.OnboardbaseProviderAuthPasscodeRefPatchArgs>? PasscodeRef { get; set; }

        public OnboardbaseProviderAuthPatchArgs()
        {
        }
        public static new OnboardbaseProviderAuthPatchArgs Empty => new OnboardbaseProviderAuthPatchArgs();
    }
}
