// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// IntegrationInfo specifies the name and version of the integration built using the 1Password Go SDK.
    /// If you don't know which name and version to use, use `DefaultIntegrationName` and `DefaultIntegrationVersion`, respectively.
    /// </summary>
    public class OnepasswordProviderSDKIntegrationInfoPatchArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name defaults to "1Password SDK".
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Version defaults to "v1.0.0".
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public OnepasswordProviderSDKIntegrationInfoPatchArgs()
        {
        }
        public static new OnepasswordProviderSDKIntegrationInfoPatchArgs Empty => new OnepasswordProviderSDKIntegrationInfoPatchArgs();
    }
}
