// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Auth defines the information necessary to authenticate against Passbolt Server
    /// </summary>
    public class PassboltProviderAuthArgs : global::Pulumi.ResourceArgs
    {
        [Input("passwordSecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.PassboltProviderAuthPasswordSecretRefArgs>? PasswordSecretRef { get; set; }

        [Input("privateKeySecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.PassboltProviderAuthPrivateKeySecretRefArgs>? PrivateKeySecretRef { get; set; }

        public PassboltProviderAuthArgs()
        {
        }
        public static new PassboltProviderAuthArgs Empty => new PassboltProviderAuthArgs();
    }
}
