// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    public class PassboltProviderPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("auth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.PassboltProviderAuthPatchArgs>? Auth { get; set; }

        /// <summary>
        /// Host defines the Passbolt Server to connect to
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        public PassboltProviderPatchArgs()
        {
        }
        public static new PassboltProviderPatchArgs Empty => new PassboltProviderPatchArgs();
    }
}
