// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Used to configure the provider. Only one provider may be set
    /// </summary>
    public class ProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("akeyless")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.AkeylessProviderArgs>? Akeyless { get; set; }

        [Input("alibaba")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.AlibabaProviderArgs>? Alibaba { get; set; }

        [Input("aws")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.AwsProviderArgs>? Aws { get; set; }

        [Input("azurekv")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.AzurekvProviderArgs>? Azurekv { get; set; }

        [Input("beyondtrust")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.BeyondtrustProviderArgs>? Beyondtrust { get; set; }

        [Input("bitwardensecretsmanager")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.BitwardensecretsmanagerProviderArgs>? Bitwardensecretsmanager { get; set; }

        [Input("chef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.ChefProviderArgs>? Chef { get; set; }

        [Input("cloudrusm")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.CloudrusmProviderArgs>? Cloudrusm { get; set; }

        [Input("conjur")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.ConjurProviderArgs>? Conjur { get; set; }

        [Input("delinea")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.DelineaProviderArgs>? Delinea { get; set; }

        [Input("device42")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.DeviceProvider42Args>? Device42 { get; set; }

        [Input("doppler")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.DopplerProviderArgs>? Doppler { get; set; }

        [Input("fake")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.FakeProviderArgs>? Fake { get; set; }

        [Input("fortanix")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.FortanixProviderArgs>? Fortanix { get; set; }

        [Input("gcpsm")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.GcpsmProviderArgs>? Gcpsm { get; set; }

        [Input("github")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.GithubProviderArgs>? Github { get; set; }

        [Input("gitlab")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.GitlabProviderArgs>? Gitlab { get; set; }

        [Input("ibm")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.IbmProviderArgs>? Ibm { get; set; }

        [Input("infisical")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.InfisicalProviderArgs>? Infisical { get; set; }

        [Input("keepersecurity")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.KeepersecurityProviderArgs>? Keepersecurity { get; set; }

        [Input("kubernetes")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.KubernetesProviderArgs>? Kubernetes { get; set; }

        [Input("onboardbase")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.OnboardbaseProviderArgs>? Onboardbase { get; set; }

        [Input("onepassword")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.OnepasswordProviderArgs>? Onepassword { get; set; }

        [Input("onepasswordSDK")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.OnepasswordProviderSDKArgs>? OnepasswordSDK { get; set; }

        [Input("oracle")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.OracleProviderArgs>? Oracle { get; set; }

        [Input("passbolt")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.PassboltProviderArgs>? Passbolt { get; set; }

        [Input("passworddepot")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.PassworddepotProviderArgs>? Passworddepot { get; set; }

        [Input("previder")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.PreviderProviderArgs>? Previder { get; set; }

        [Input("pulumi")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.PulumiProviderArgs>? Pulumi { get; set; }

        [Input("scaleway")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.ScalewayProviderArgs>? Scaleway { get; set; }

        [Input("secretserver")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.SecretserverProviderArgs>? Secretserver { get; set; }

        [Input("senhasegura")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.SenhaseguraProviderArgs>? Senhasegura { get; set; }

        [Input("vault")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.VaultProviderArgs>? Vault { get; set; }

        [Input("webhook")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.WebhookProviderArgs>? Webhook { get; set; }

        [Input("yandexcertificatemanager")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.YandexcertificatemanagerProviderArgs>? Yandexcertificatemanager { get; set; }

        [Input("yandexlockbox")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.YandexlockboxProviderArgs>? Yandexlockbox { get; set; }

        public ProviderArgs()
        {
        }
        public static new ProviderArgs Empty => new ProviderArgs();
    }
}
