// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// SecretStoreSpec defines the desired state of SecretStore.
    /// </summary>
    public class SecretStoreSpecArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.SecretStoreSpecConditionsArgs>? _conditions;

        /// <summary>
        /// Used to constraint a ClusterSecretStore to specific namespaces. Relevant only to ClusterSecretStore
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.SecretStoreSpecConditionsArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.SecretStoreSpecConditionsArgs>());
            set => _conditions = value;
        }

        /// <summary>
        /// Used to select the correct ESO controller (think: ingress.ingressClassName)
        /// The ESO controller is instantiated with a specific controller name and filters ES based on this property
        /// </summary>
        [Input("controller")]
        public Input<string>? Controller { get; set; }

        [Input("provider")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.ProviderArgs>? Provider { get; set; }

        /// <summary>
        /// Used to configure store refresh interval in seconds. Empty or 0 will default to the controller config.
        /// </summary>
        [Input("refreshInterval")]
        public Input<int>? RefreshInterval { get; set; }

        [Input("retrySettings")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.SecretStoreSpecRetrySettingsArgs>? RetrySettings { get; set; }

        public SecretStoreSpecArgs()
        {
        }
        public static new SecretStoreSpecArgs Empty => new SecretStoreSpecArgs();
    }
}
