// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Username is the secret server account username.
    /// </summary>
    public class SecretserverProviderUsernamePatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("secretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.SecretserverProviderUsernameSecretRefPatchArgs>? SecretRef { get; set; }

        /// <summary>
        /// Value can be specified directly to set a value without using a secret.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public SecretserverProviderUsernamePatchArgs()
        {
        }
        public static new SecretserverProviderUsernamePatchArgs Empty => new SecretserverProviderUsernamePatchArgs();
    }
}
