// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Senhasegura configures this store to sync secrets using senhasegura provider
    /// </summary>
    public class SenhaseguraProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("auth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.SenhaseguraProviderAuthArgs>? Auth { get; set; }

        /// <summary>
        /// IgnoreSslCertificate defines if SSL certificate must be ignored
        /// </summary>
        [Input("ignoreSslCertificate")]
        public Input<bool>? IgnoreSslCertificate { get; set; }

        /// <summary>
        /// Module defines which senhasegura module should be used to get secrets
        /// </summary>
        [Input("module")]
        public Input<string>? Module { get; set; }

        /// <summary>
        /// URL of senhasegura
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public SenhaseguraProviderArgs()
        {
        }
        public static new SenhaseguraProviderArgs Empty => new SenhaseguraProviderArgs();
    }
}
