// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// Cert authenticates with TLS Certificates by passing client certificate, private key and ca certificate
    /// Cert authentication method
    /// </summary>
    public class VaultProviderAuthCertPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("clientCert")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.VaultProviderAuthCertClientCertPatchArgs>? ClientCert { get; set; }

        [Input("secretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.VaultProviderAuthCertSecretRefPatchArgs>? SecretRef { get; set; }

        public VaultProviderAuthCertPatchArgs()
        {
        }
        public static new VaultProviderAuthCertPatchArgs Empty => new VaultProviderAuthCertPatchArgs();
    }
}
