// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// The configuration used for client side related TLS communication, when the Vault server
    /// requires mutual authentication. Only used if the Server URL is using HTTPS protocol.
    /// This parameter is ignored for plain HTTP protocol connection.
    /// It's worth noting this configuration is different from the "TLS certificates auth method",
    /// which is available under the `auth.cert` section.
    /// </summary>
    public class VaultProviderTlsPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("certSecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.VaultProviderTlsCertSecretRefPatchArgs>? CertSecretRef { get; set; }

        [Input("keySecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.VaultProviderTlsKeySecretRefPatchArgs>? KeySecretRef { get; set; }

        public VaultProviderTlsPatchArgs()
        {
        }
        public static new VaultProviderTlsPatchArgs Empty => new VaultProviderTlsPatchArgs();
    }
}
