// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1
{

    /// <summary>
    /// NTLMProtocol configures the store to use NTLM for auth
    /// </summary>
    public class WebhookProviderAuthNtlmPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("passwordSecret")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.WebhookProviderAuthNtlmPasswordSecretPatchArgs>? PasswordSecret { get; set; }

        [Input("usernameSecret")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1.WebhookProviderAuthNtlmUsernameSecretPatchArgs>? UsernameSecret { get; set; }

        public WebhookProviderAuthNtlmPatchArgs()
        {
        }
        public static new WebhookProviderAuthNtlmPatchArgs Empty => new WebhookProviderAuthNtlmPatchArgs();
    }
}
