// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// The AccessKeySecret is used for authentication
    /// </summary>
    public class AlibabaProviderAuthSecretRefAccessKeySecretSecretRefArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A key in the referenced Secret.
        /// Some instances of this field may be defaulted, in others it may be required.
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// The name of the Secret resource being referred to.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The namespace of the Secret resource being referred to.
        /// Ignored if referent is not cluster-scoped, otherwise defaults to the namespace of the referent.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        public AlibabaProviderAuthSecretRefAccessKeySecretSecretRefArgs()
        {
        }
        public static new AlibabaProviderAuthSecretRefAccessKeySecretSecretRefArgs Empty => new AlibabaProviderAuthSecretRefAccessKeySecretSecretRefArgs();
    }
}
