// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// AWSAuthSecretRef holds secret references for AWS credentials
    /// both AccessKeyID and SecretAccessKey must be defined in order to properly authenticate.
    /// </summary>
    public class AwsProviderAuthSecretRefPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessKeyIDSecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.AwsProviderAuthSecretRefAccessKeyIDSecretRefPatchArgs>? AccessKeyIDSecretRef { get; set; }

        [Input("secretAccessKeySecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.AwsProviderAuthSecretRefSecretAccessKeySecretRefPatchArgs>? SecretAccessKeySecretRef { get; set; }

        [Input("sessionTokenSecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.AwsProviderAuthSecretRefSessionTokenSecretRefPatchArgs>? SessionTokenSecretRef { get; set; }

        public AwsProviderAuthSecretRefPatchArgs()
        {
        }
        public static new AwsProviderAuthSecretRefPatchArgs Empty => new AwsProviderAuthSecretRefPatchArgs();
    }
}
