// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// BitwardenSecretsManager configures this store to sync secrets using BitwardenSecretsManager provider
    /// </summary>
    public class BitwardensecretsmanagerProviderPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiURL")]
        public Input<string>? ApiURL { get; set; }

        [Input("auth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.BitwardensecretsmanagerProviderAuthPatchArgs>? Auth { get; set; }

        [Input("bitwardenServerSDKURL")]
        public Input<string>? BitwardenServerSDKURL { get; set; }

        /// <summary>
        /// Base64 encoded certificate for the bitwarden server sdk. The sdk MUST run with HTTPS to make sure no MITM attack
        /// can be performed.
        /// </summary>
        [Input("caBundle")]
        public Input<string>? CaBundle { get; set; }

        [Input("caProvider")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.BitwardensecretsmanagerProviderCaProviderPatchArgs>? CaProvider { get; set; }

        [Input("identityURL")]
        public Input<string>? IdentityURL { get; set; }

        /// <summary>
        /// OrganizationID determines which organization this secret store manages.
        /// </summary>
        [Input("organizationID")]
        public Input<string>? OrganizationID { get; set; }

        /// <summary>
        /// ProjectID determines which project this secret store manages.
        /// </summary>
        [Input("projectID")]
        public Input<string>? ProjectID { get; set; }

        public BitwardensecretsmanagerProviderPatchArgs()
        {
        }
        public static new BitwardensecretsmanagerProviderPatchArgs Empty => new BitwardensecretsmanagerProviderPatchArgs();
    }
}
