// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Auth defines the information necessary to authenticate against chef Server
    /// </summary>
    public class ChefProviderAuthPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("secretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ChefProviderAuthSecretRefPatchArgs>? SecretRef { get; set; }

        public ChefProviderAuthPatchArgs()
        {
        }
        public static new ChefProviderAuthPatchArgs Empty => new ChefProviderAuthPatchArgs();
    }
}
