// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    public class ClusterExternalSecretSpecExternalSecretSpecDataFromRewriteArgs : global::Pulumi.ResourceArgs
    {
        [Input("regexp")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecDataFromRewriteRegexpArgs>? Regexp { get; set; }

        [Input("transform")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecDataFromRewriteTransformArgs>? Transform { get; set; }

        public ClusterExternalSecretSpecExternalSecretSpecDataFromRewriteArgs()
        {
        }
        public static new ClusterExternalSecretSpecExternalSecretSpecDataFromRewriteArgs Empty => new ClusterExternalSecretSpecExternalSecretSpecDataFromRewriteArgs();
    }
}
