// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    public class ClusterExternalSecretSpecExternalSecretSpecDataFromPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("extract")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecDataFromExtractPatchArgs>? Extract { get; set; }

        [Input("find")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecDataFromFindPatchArgs>? Find { get; set; }

        [Input("rewrite")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecDataFromRewritePatchArgs>? _rewrite;

        /// <summary>
        /// Used to rewrite secret Keys after getting them from the secret Provider
        /// Multiple Rewrite operations can be provided. They are applied in a layered order (first to last)
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecDataFromRewritePatchArgs> Rewrite
        {
            get => _rewrite ?? (_rewrite = new InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecDataFromRewritePatchArgs>());
            set => _rewrite = value;
        }

        [Input("sourceRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ClusterExternalSecretSpecExternalSecretSpecDataFromSourceRefPatchArgs>? SourceRef { get; set; }

        public ClusterExternalSecretSpecExternalSecretSpecDataFromPatchArgs()
        {
        }
        public static new ClusterExternalSecretSpecExternalSecretSpecDataFromPatchArgs Empty => new ClusterExternalSecretSpecExternalSecretSpecDataFromPatchArgs();
    }
}
