// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Defines authentication settings for connecting to Conjur.
    /// </summary>
    public class ConjurProviderAuthArgs : global::Pulumi.ResourceArgs
    {
        [Input("apikey")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ConjurProviderAuthApikeyArgs>? Apikey { get; set; }

        [Input("jwt")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ConjurProviderAuthJwtArgs>? Jwt { get; set; }

        public ConjurProviderAuthArgs()
        {
        }
        public static new ConjurProviderAuthArgs Empty => new ConjurProviderAuthArgs();
    }
}
