// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    public class DeviceProvider42AuthSecretRefPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("credentials")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.DeviceProvider42AuthSecretRefCredentialsPatchArgs>? Credentials { get; set; }

        public DeviceProvider42AuthSecretRefPatchArgs()
        {
        }
        public static new DeviceProvider42AuthSecretRefPatchArgs Empty => new DeviceProvider42AuthSecretRefPatchArgs();
    }
}
