// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Doppler configures this store to sync secrets using the Doppler provider
    /// </summary>
    public class DopplerProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("auth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.DopplerProviderAuthArgs>? Auth { get; set; }

        /// <summary>
        /// Doppler config (required if not using a Service Token)
        /// </summary>
        [Input("config")]
        public Input<string>? Config { get; set; }

        /// <summary>
        /// Format enables the downloading of secrets as a file (string)
        /// </summary>
        [Input("format")]
        public Input<string>? Format { get; set; }

        /// <summary>
        /// Environment variable compatible name transforms that change secret names to a different format
        /// </summary>
        [Input("nameTransformer")]
        public Input<string>? NameTransformer { get; set; }

        /// <summary>
        /// Doppler project (required if not using a Service Token)
        /// </summary>
        [Input("project")]
        public Input<string>? Project { get; set; }

        public DopplerProviderArgs()
        {
        }
        public static new DopplerProviderArgs Empty => new DopplerProviderArgs();
    }
}
