// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Finds secrets based on the name.
    /// </summary>
    public class ExternalSecretSpecDataFromFindNameArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Finds secrets base
        /// </summary>
        [Input("regexp")]
        public Input<string>? Regexp { get; set; }

        public ExternalSecretSpecDataFromFindNameArgs()
        {
        }
        public static new ExternalSecretSpecDataFromFindNameArgs Empty => new ExternalSecretSpecDataFromFindNameArgs();
    }
}
