// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// ExternalSecretData defines the connection between the Kubernetes Secret key (spec.data.&lt;key&gt;) and the Provider data.
    /// </summary>
    public class ExternalSecretSpecDataPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("remoteRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ExternalSecretSpecDataRemoteRefPatchArgs>? RemoteRef { get; set; }

        /// <summary>
        /// The key in the Kubernetes Secret to store the value.
        /// </summary>
        [Input("secretKey")]
        public Input<string>? SecretKey { get; set; }

        [Input("sourceRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ExternalSecretSpecDataSourceRefPatchArgs>? SourceRef { get; set; }

        public ExternalSecretSpecDataPatchArgs()
        {
        }
        public static new ExternalSecretSpecDataPatchArgs Empty => new ExternalSecretSpecDataPatchArgs();
    }
}
