// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    public class ExternalSecretSpecDataFromRewriteArgs : global::Pulumi.ResourceArgs
    {
        [Input("regexp")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ExternalSecretSpecDataFromRewriteRegexpArgs>? Regexp { get; set; }

        [Input("transform")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ExternalSecretSpecDataFromRewriteTransformArgs>? Transform { get; set; }

        public ExternalSecretSpecDataFromRewriteArgs()
        {
        }
        public static new ExternalSecretSpecDataFromRewriteArgs Empty => new ExternalSecretSpecDataFromRewriteArgs();
    }
}
