// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    public class ExternalSecretSpecTargetTemplateTemplateFromArgs : global::Pulumi.ResourceArgs
    {
        [Input("configMap")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ExternalSecretSpecTargetTemplateTemplateFromConfigMapArgs>? ConfigMap { get; set; }

        [Input("literal")]
        public Input<string>? Literal { get; set; }

        [Input("secret")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ExternalSecretSpecTargetTemplateTemplateFromSecretArgs>? Secret { get; set; }

        [Input("target")]
        public Input<string>? Target { get; set; }

        public ExternalSecretSpecTargetTemplateTemplateFromArgs()
        {
        }
        public static new ExternalSecretSpecTargetTemplateTemplateFromArgs Empty => new ExternalSecretSpecTargetTemplateTemplateFromArgs();
    }
}
