// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// ExternalSecretTarget defines the Kubernetes Secret to be created
    /// There can be only one target per ExternalSecret.
    /// </summary>
    public class ExternalSecretSpecTargetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// CreationPolicy defines rules on how to create the resulting Secret.
        /// Defaults to "Owner"
        /// </summary>
        [Input("creationPolicy")]
        public Input<string>? CreationPolicy { get; set; }

        /// <summary>
        /// DeletionPolicy defines rules on how to delete the resulting Secret.
        /// Defaults to "Retain"
        /// </summary>
        [Input("deletionPolicy")]
        public Input<string>? DeletionPolicy { get; set; }

        /// <summary>
        /// Immutable defines if the final secret will be immutable
        /// </summary>
        [Input("immutable")]
        public Input<bool>? Immutable { get; set; }

        /// <summary>
        /// The name of the Secret resource to be managed.
        /// Defaults to the .metadata.name of the ExternalSecret resource
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("template")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ExternalSecretSpecTargetTemplateArgs>? Template { get; set; }

        public ExternalSecretSpecTargetArgs()
        {
        }
        public static new ExternalSecretSpecTargetArgs Empty => new ExternalSecretSpecTargetArgs();
    }
}
