// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Used to find secrets based on tags or regular expressions
    /// Note: Find does not support sourceRef.Generator or sourceRef.GeneratorRef.
    /// </summary>
    public class ExternalSecretSpecDataFromFindPatchArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Used to define a conversion Strategy
        /// </summary>
        [Input("conversionStrategy")]
        public Input<string>? ConversionStrategy { get; set; }

        /// <summary>
        /// Used to define a decoding Strategy
        /// </summary>
        [Input("decodingStrategy")]
        public Input<string>? DecodingStrategy { get; set; }

        [Input("name")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ExternalSecretSpecDataFromFindNamePatchArgs>? Name { get; set; }

        /// <summary>
        /// A root path to start the find operations.
        /// </summary>
        [Input("path")]
        public Input<string>? Path { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// Find secrets based on tags.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        public ExternalSecretSpecDataFromFindPatchArgs()
        {
        }
        public static new ExternalSecretSpecDataFromFindPatchArgs Empty => new ExternalSecretSpecDataFromFindPatchArgs();
    }
}
