// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// SourceRef allows you to override the source
    /// from which the value will be pulled.
    /// </summary>
    public class ExternalSecretSpecDataSourceRefArgs : global::Pulumi.ResourceArgs
    {
        [Input("generatorRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ExternalSecretSpecDataSourceRefGeneratorRefArgs>? GeneratorRef { get; set; }

        [Input("storeRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ExternalSecretSpecDataSourceRefStoreRefArgs>? StoreRef { get; set; }

        public ExternalSecretSpecDataSourceRefArgs()
        {
        }
        public static new ExternalSecretSpecDataSourceRefArgs Empty => new ExternalSecretSpecDataSourceRefArgs();
    }
}
