// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Fake configures a store with static key/value pairs
    /// </summary>
    public class FakeProviderPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("data")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.FakeProviderDataPatchArgs>? _data;
        public InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.FakeProviderDataPatchArgs> Data
        {
            get => _data ?? (_data = new InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.FakeProviderDataPatchArgs>());
            set => _data = value;
        }

        public FakeProviderPatchArgs()
        {
        }
        public static new FakeProviderPatchArgs Empty => new FakeProviderPatchArgs();
    }
}
