// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Auth defines the information necessary to authenticate against GCP
    /// </summary>
    public class GcpsmProviderAuthPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("secretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.GcpsmProviderAuthSecretRefPatchArgs>? SecretRef { get; set; }

        [Input("workloadIdentity")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.GcpsmProviderAuthWorkloadIdentityPatchArgs>? WorkloadIdentity { get; set; }

        public GcpsmProviderAuthPatchArgs()
        {
        }
        public static new GcpsmProviderAuthPatchArgs Empty => new GcpsmProviderAuthPatchArgs();
    }
}
