// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    public class GitlabProviderAuthSecretRefArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessToken")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.GitlabProviderAuthSecretRefAccessTokenArgs>? AccessToken { get; set; }

        public GitlabProviderAuthSecretRefArgs()
        {
        }
        public static new GitlabProviderAuthSecretRefArgs Empty => new GitlabProviderAuthSecretRefArgs();
    }
}
