// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    public class IbmProviderAuthSecretRefArgs : global::Pulumi.ResourceArgs
    {
        [Input("secretApiKeySecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.IbmProviderAuthSecretRefSecretApiKeySecretRefArgs>? SecretApiKeySecretRef { get; set; }

        public IbmProviderAuthSecretRefArgs()
        {
        }
        public static new IbmProviderAuthSecretRefArgs Empty => new IbmProviderAuthSecretRefArgs();
    }
}
