// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Auth configures how the Operator authenticates with the Infisical API
    /// </summary>
    public class InfisicalProviderAuthArgs : global::Pulumi.ResourceArgs
    {
        [Input("universalAuthCredentials")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.InfisicalProviderAuthUniversalAuthCredentialsArgs>? UniversalAuthCredentials { get; set; }

        public InfisicalProviderAuthArgs()
        {
        }
        public static new InfisicalProviderAuthArgs Empty => new InfisicalProviderAuthArgs();
    }
}
