// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Kubernetes configures this store to sync secrets using a Kubernetes cluster provider
    /// </summary>
    public class KubernetesProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("auth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.KubernetesProviderAuthArgs>? Auth { get; set; }

        [Input("authRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.KubernetesProviderAuthRefArgs>? AuthRef { get; set; }

        /// <summary>
        /// Remote namespace to fetch the secrets from
        /// </summary>
        [Input("remoteNamespace")]
        public Input<string>? RemoteNamespace { get; set; }

        [Input("server")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.KubernetesProviderServerArgs>? Server { get; set; }

        public KubernetesProviderArgs()
        {
        }
        public static new KubernetesProviderArgs Empty => new KubernetesProviderArgs();
    }
}
