// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// use static token to authenticate with
    /// </summary>
    public class KubernetesProviderAuthTokenArgs : global::Pulumi.ResourceArgs
    {
        [Input("bearerToken")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.KubernetesProviderAuthTokenBearerTokenArgs>? BearerToken { get; set; }

        public KubernetesProviderAuthTokenArgs()
        {
        }
        public static new KubernetesProviderAuthTokenArgs Empty => new KubernetesProviderAuthTokenArgs();
    }
}
