// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// OnePasswordAuthSecretRef holds secret references for 1Password credentials.
    /// </summary>
    public class OnepasswordProviderAuthSecretRefArgs : global::Pulumi.ResourceArgs
    {
        [Input("connectTokenSecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.OnepasswordProviderAuthSecretRefConnectTokenSecretRefArgs>? ConnectTokenSecretRef { get; set; }

        public OnepasswordProviderAuthSecretRefArgs()
        {
        }
        public static new OnepasswordProviderAuthSecretRefArgs Empty => new OnepasswordProviderAuthSecretRefArgs();
    }
}
