// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    public class PassboltProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("auth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.PassboltProviderAuthArgs>? Auth { get; set; }

        /// <summary>
        /// Host defines the Passbolt Server to connect to
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        public PassboltProviderArgs()
        {
        }
        public static new PassboltProviderArgs Empty => new PassboltProviderArgs();
    }
}
