// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Configures a store to sync secrets with a Password Depot instance.
    /// </summary>
    public class PassworddepotProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("auth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.PassworddepotProviderAuthArgs>? Auth { get; set; }

        /// <summary>
        /// Database to use as source
        /// </summary>
        [Input("database")]
        public Input<string>? Database { get; set; }

        /// <summary>
        /// URL configures the Password Depot instance URL.
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        public PassworddepotProviderArgs()
        {
        }
        public static new PassworddepotProviderArgs Empty => new PassworddepotProviderArgs();
    }
}
