// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Used to configure the provider. Only one provider may be set
    /// </summary>
    public class PatchProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("akeyless")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.AkeylessProviderPatchArgs>? Akeyless { get; set; }

        [Input("alibaba")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.AlibabaProviderPatchArgs>? Alibaba { get; set; }

        [Input("aws")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.AwsProviderPatchArgs>? Aws { get; set; }

        [Input("azurekv")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.AzurekvProviderPatchArgs>? Azurekv { get; set; }

        [Input("beyondtrust")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.BeyondtrustProviderPatchArgs>? Beyondtrust { get; set; }

        [Input("bitwardensecretsmanager")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.BitwardensecretsmanagerProviderPatchArgs>? Bitwardensecretsmanager { get; set; }

        [Input("chef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ChefProviderPatchArgs>? Chef { get; set; }

        [Input("cloudrusm")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.CloudrusmProviderPatchArgs>? Cloudrusm { get; set; }

        [Input("conjur")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ConjurProviderPatchArgs>? Conjur { get; set; }

        [Input("delinea")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.DelineaProviderPatchArgs>? Delinea { get; set; }

        [Input("device42")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.DeviceProvider42PatchArgs>? Device42 { get; set; }

        [Input("doppler")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.DopplerProviderPatchArgs>? Doppler { get; set; }

        [Input("fake")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.FakeProviderPatchArgs>? Fake { get; set; }

        [Input("fortanix")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.FortanixProviderPatchArgs>? Fortanix { get; set; }

        [Input("gcpsm")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.GcpsmProviderPatchArgs>? Gcpsm { get; set; }

        [Input("github")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.GithubProviderPatchArgs>? Github { get; set; }

        [Input("gitlab")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.GitlabProviderPatchArgs>? Gitlab { get; set; }

        [Input("ibm")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.IbmProviderPatchArgs>? Ibm { get; set; }

        [Input("infisical")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.InfisicalProviderPatchArgs>? Infisical { get; set; }

        [Input("keepersecurity")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.KeepersecurityProviderPatchArgs>? Keepersecurity { get; set; }

        [Input("kubernetes")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.KubernetesProviderPatchArgs>? Kubernetes { get; set; }

        [Input("onboardbase")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.OnboardbaseProviderPatchArgs>? Onboardbase { get; set; }

        [Input("onepassword")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.OnepasswordProviderPatchArgs>? Onepassword { get; set; }

        [Input("oracle")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.OracleProviderPatchArgs>? Oracle { get; set; }

        [Input("passbolt")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.PassboltProviderPatchArgs>? Passbolt { get; set; }

        [Input("passworddepot")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.PassworddepotProviderPatchArgs>? Passworddepot { get; set; }

        [Input("previder")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.PreviderProviderPatchArgs>? Previder { get; set; }

        [Input("pulumi")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.PulumiProviderPatchArgs>? Pulumi { get; set; }

        [Input("scaleway")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.ScalewayProviderPatchArgs>? Scaleway { get; set; }

        [Input("secretserver")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.SecretserverProviderPatchArgs>? Secretserver { get; set; }

        [Input("senhasegura")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.SenhaseguraProviderPatchArgs>? Senhasegura { get; set; }

        [Input("vault")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderPatchArgs>? Vault { get; set; }

        [Input("webhook")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.WebhookProviderPatchArgs>? Webhook { get; set; }

        [Input("yandexcertificatemanager")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.YandexcertificatemanagerProviderPatchArgs>? Yandexcertificatemanager { get; set; }

        [Input("yandexlockbox")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.YandexlockboxProviderPatchArgs>? Yandexlockbox { get; set; }

        public PatchProviderArgs()
        {
        }
        public static new PatchProviderArgs Empty => new PatchProviderArgs();
    }
}
