// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Previder configures this store to sync secrets using the Previder provider
    /// </summary>
    public class PreviderProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("auth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.PreviderProviderAuthArgs>? Auth { get; set; }

        [Input("baseUri")]
        public Input<string>? BaseUri { get; set; }

        public PreviderProviderArgs()
        {
        }
        public static new PreviderProviderArgs Empty => new PreviderProviderArgs();
    }
}
