// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Used to configure http retries if failed
    /// </summary>
    public class SecretStoreSpecRetrySettingsPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("maxRetries")]
        public Input<int>? MaxRetries { get; set; }

        [Input("retryInterval")]
        public Input<string>? RetryInterval { get; set; }

        public SecretStoreSpecRetrySettingsPatchArgs()
        {
        }
        public static new SecretStoreSpecRetrySettingsPatchArgs Empty => new SecretStoreSpecRetrySettingsPatchArgs();
    }
}
