// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Kubernetes authenticates with Vault by passing the ServiceAccount
    /// token stored in the named Secret resource to the Vault server.
    /// </summary>
    public class VaultProviderAuthKubernetesPatchArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Path where the Kubernetes authentication backend is mounted in Vault, e.g:
        /// "kubernetes"
        /// </summary>
        [Input("mountPath")]
        public Input<string>? MountPath { get; set; }

        /// <summary>
        /// A required field containing the Vault Role to assume. A Role binds a
        /// Kubernetes ServiceAccount with a set of Vault policies.
        /// </summary>
        [Input("role")]
        public Input<string>? Role { get; set; }

        [Input("secretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderAuthKubernetesSecretRefPatchArgs>? SecretRef { get; set; }

        [Input("serviceAccountRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderAuthKubernetesServiceAccountRefPatchArgs>? ServiceAccountRef { get; set; }

        public VaultProviderAuthKubernetesPatchArgs()
        {
        }
        public static new VaultProviderAuthKubernetesPatchArgs Empty => new VaultProviderAuthKubernetesPatchArgs();
    }
}
