// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Specify credentials in a Secret object
    /// </summary>
    public class VaultProviderAuthIamSecretRefPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessKeyIDSecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderAuthIamSecretRefAccessKeyIDSecretRefPatchArgs>? AccessKeyIDSecretRef { get; set; }

        [Input("secretAccessKeySecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderAuthIamSecretRefSecretAccessKeySecretRefPatchArgs>? SecretAccessKeySecretRef { get; set; }

        [Input("sessionTokenSecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderAuthIamSecretRefSessionTokenSecretRefPatchArgs>? SessionTokenSecretRef { get; set; }

        public VaultProviderAuthIamSecretRefPatchArgs()
        {
        }
        public static new VaultProviderAuthIamSecretRefPatchArgs Empty => new VaultProviderAuthIamSecretRefPatchArgs();
    }
}
