// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Specify a service account with IRSA enabled
    /// </summary>
    public class VaultProviderAuthIamJwtPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("serviceAccountRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderAuthIamJwtServiceAccountRefPatchArgs>? ServiceAccountRef { get; set; }

        public VaultProviderAuthIamJwtPatchArgs()
        {
        }
        public static new VaultProviderAuthIamJwtPatchArgs Empty => new VaultProviderAuthIamJwtPatchArgs();
    }
}
