// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Auth configures how secret-manager authenticates with the Vault server.
    /// </summary>
    public class VaultProviderAuthPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("appRole")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderAuthAppRolePatchArgs>? AppRole { get; set; }

        [Input("cert")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderAuthCertPatchArgs>? Cert { get; set; }

        [Input("iam")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderAuthIamPatchArgs>? Iam { get; set; }

        [Input("jwt")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderAuthJwtPatchArgs>? Jwt { get; set; }

        [Input("kubernetes")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderAuthKubernetesPatchArgs>? Kubernetes { get; set; }

        [Input("ldap")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderAuthLdapPatchArgs>? Ldap { get; set; }

        /// <summary>
        /// Name of the vault namespace to authenticate to. This can be different than the namespace your secret is in.
        /// Namespaces is a set of features within Vault Enterprise that allows
        /// Vault environments to support Secure Multi-tenancy. e.g: "ns1".
        /// More about namespaces can be found here https://www.vaultproject.io/docs/enterprise/namespaces
        /// This will default to Vault.Namespace field if set, or empty otherwise
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        [Input("tokenSecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderAuthTokenSecretRefPatchArgs>? TokenSecretRef { get; set; }

        [Input("userPass")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderAuthUserPassPatchArgs>? UserPass { get; set; }

        public VaultProviderAuthPatchArgs()
        {
        }
        public static new VaultProviderAuthPatchArgs Empty => new VaultProviderAuthPatchArgs();
    }
}
