// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// The provider for the CA bundle to use to validate Vault server certificate.
    /// </summary>
    public class VaultProviderCaProviderArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The key where the CA certificate can be found in the Secret or ConfigMap.
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// The name of the object located at the provider type.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The namespace the Provider type is in.
        /// Can only be defined when used in a ClusterSecretStore.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        /// <summary>
        /// The type of provider to use such as "Secret", or "ConfigMap".
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public VaultProviderCaProviderArgs()
        {
        }
        public static new VaultProviderCaProviderArgs Empty => new VaultProviderCaProviderArgs();
    }
}
