// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// AppRole authenticates with Vault using the App Role auth mechanism,
    /// with the role and secret stored in a Kubernetes Secret resource.
    /// </summary>
    public class VaultProviderAuthAppRoleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Path where the App Role authentication backend is mounted
        /// in Vault, e.g: "approle"
        /// </summary>
        [Input("path")]
        public Input<string>? Path { get; set; }

        /// <summary>
        /// RoleID configured in the App Role authentication backend when setting
        /// up the authentication backend in Vault.
        /// </summary>
        [Input("roleId")]
        public Input<string>? RoleId { get; set; }

        [Input("roleRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderAuthAppRoleRoleRefArgs>? RoleRef { get; set; }

        [Input("secretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderAuthAppRoleSecretRefArgs>? SecretRef { get; set; }

        public VaultProviderAuthAppRoleArgs()
        {
        }
        public static new VaultProviderAuthAppRoleArgs Empty => new VaultProviderAuthAppRoleArgs();
    }
}
