// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Vault configures this store to sync secrets using Hashi provider
    /// </summary>
    public class VaultProviderPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("auth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderAuthPatchArgs>? Auth { get; set; }

        /// <summary>
        /// PEM encoded CA bundle used to validate Vault server certificate. Only used
        /// if the Server URL is using HTTPS protocol. This parameter is ignored for
        /// plain HTTP protocol connection. If not set the system root certificates
        /// are used to validate the TLS connection.
        /// </summary>
        [Input("caBundle")]
        public Input<string>? CaBundle { get; set; }

        [Input("caProvider")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderCaProviderPatchArgs>? CaProvider { get; set; }

        /// <summary>
        /// ForwardInconsistent tells Vault to forward read-after-write requests to the Vault
        /// leader instead of simply retrying within a loop. This can increase performance if
        /// the option is enabled serverside.
        /// https://www.vaultproject.io/docs/configuration/replication#allow_forwarding_via_header
        /// </summary>
        [Input("forwardInconsistent")]
        public Input<bool>? ForwardInconsistent { get; set; }

        [Input("headers")]
        private InputMap<string>? _headers;

        /// <summary>
        /// Headers to be added in Vault request
        /// </summary>
        public InputMap<string> Headers
        {
            get => _headers ?? (_headers = new InputMap<string>());
            set => _headers = value;
        }

        /// <summary>
        /// Name of the vault namespace. Namespaces is a set of features within Vault Enterprise that allows
        /// Vault environments to support Secure Multi-tenancy. e.g: "ns1".
        /// More about namespaces can be found here https://www.vaultproject.io/docs/enterprise/namespaces
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        /// <summary>
        /// Path is the mount path of the Vault KV backend endpoint, e.g:
        /// "secret". The v2 KV secret engine version specific "/data" path suffix
        /// for fetching secrets from Vault is optional and will be appended
        /// if not present in specified path.
        /// </summary>
        [Input("path")]
        public Input<string>? Path { get; set; }

        /// <summary>
        /// ReadYourWrites ensures isolated read-after-write semantics by
        /// providing discovered cluster replication states in each request.
        /// More information about eventual consistency in Vault can be found here
        /// https://www.vaultproject.io/docs/enterprise/consistency
        /// </summary>
        [Input("readYourWrites")]
        public Input<bool>? ReadYourWrites { get; set; }

        /// <summary>
        /// Server is the connection address for the Vault server, e.g: "https://vault.example.com:8200".
        /// </summary>
        [Input("server")]
        public Input<string>? Server { get; set; }

        [Input("tls")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.VaultProviderTlsPatchArgs>? Tls { get; set; }

        /// <summary>
        /// Version is the Vault KV secret engine version. This can be either "v1" or
        /// "v2". Version defaults to "v2".
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public VaultProviderPatchArgs()
        {
        }
        public static new VaultProviderPatchArgs Empty => new VaultProviderPatchArgs();
    }
}
