// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Auth specifies a authorization protocol. Only one protocol may be set.
    /// </summary>
    public class WebhookProviderAuthPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("ntlm")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.WebhookProviderAuthNtlmPatchArgs>? Ntlm { get; set; }

        public WebhookProviderAuthPatchArgs()
        {
        }
        public static new WebhookProviderAuthPatchArgs Empty => new WebhookProviderAuthPatchArgs();
    }
}
