// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Webhook configures this store to sync secrets using a generic templated webhook
    /// </summary>
    public class WebhookProviderPatchArgs : global::Pulumi.ResourceArgs
    {
        [Input("auth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.WebhookProviderAuthPatchArgs>? Auth { get; set; }

        /// <summary>
        /// Body
        /// </summary>
        [Input("body")]
        public Input<string>? Body { get; set; }

        /// <summary>
        /// PEM encoded CA bundle used to validate webhook server certificate. Only used
        /// if the Server URL is using HTTPS protocol. This parameter is ignored for
        /// plain HTTP protocol connection. If not set the system root certificates
        /// are used to validate the TLS connection.
        /// </summary>
        [Input("caBundle")]
        public Input<string>? CaBundle { get; set; }

        [Input("caProvider")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.WebhookProviderCaProviderPatchArgs>? CaProvider { get; set; }

        [Input("headers")]
        private InputMap<string>? _headers;

        /// <summary>
        /// Headers
        /// </summary>
        public InputMap<string> Headers
        {
            get => _headers ?? (_headers = new InputMap<string>());
            set => _headers = value;
        }

        /// <summary>
        /// Webhook Method
        /// </summary>
        [Input("method")]
        public Input<string>? Method { get; set; }

        [Input("result")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.WebhookProviderResultPatchArgs>? Result { get; set; }

        [Input("secrets")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.WebhookProviderSecretsPatchArgs>? _secrets;

        /// <summary>
        /// Secrets to fill in templates
        /// These secrets will be passed to the templating function as key value pairs under the given name
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.WebhookProviderSecretsPatchArgs> Secrets
        {
            get => _secrets ?? (_secrets = new InputList<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.WebhookProviderSecretsPatchArgs>());
            set => _secrets = value;
        }

        /// <summary>
        /// Timeout
        /// </summary>
        [Input("timeout")]
        public Input<string>? Timeout { get; set; }

        /// <summary>
        /// Webhook url to call
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public WebhookProviderPatchArgs()
        {
        }
        public static new WebhookProviderPatchArgs Empty => new WebhookProviderPatchArgs();
    }
}
