// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// Auth defines the information necessary to authenticate against Yandex Certificate Manager
    /// </summary>
    public class YandexcertificatemanagerProviderAuthArgs : global::Pulumi.ResourceArgs
    {
        [Input("authorizedKeySecretRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.YandexcertificatemanagerProviderAuthAuthorizedKeySecretRefArgs>? AuthorizedKeySecretRef { get; set; }

        public YandexcertificatemanagerProviderAuthArgs()
        {
        }
        public static new YandexcertificatemanagerProviderAuthArgs Empty => new YandexcertificatemanagerProviderAuthArgs();
    }
}
