// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1
{

    /// <summary>
    /// YandexLockbox configures this store to sync secrets using Yandex Lockbox provider
    /// </summary>
    public class YandexlockboxProviderArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Yandex.Cloud API endpoint (e.g. 'api.cloud.yandex.net:443')
        /// </summary>
        [Input("apiEndpoint")]
        public Input<string>? ApiEndpoint { get; set; }

        [Input("auth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.YandexlockboxProviderAuthArgs>? Auth { get; set; }

        [Input("caProvider")]
        public Input<Pulumi.Kubernetes.Types.Inputs.ExternalSecrets.V1Beta1.YandexlockboxProviderCaProviderArgs>? CaProvider { get; set; }

        public YandexlockboxProviderArgs()
        {
        }
        public static new YandexlockboxProviderArgs Empty => new YandexlockboxProviderArgs();
    }
}
